/**
 * 模型图标路径：优先使用 public/images/models/logos 下重命名后的图标
 * 根据模型 id 解析为 logos 中的文件名（无则回退到旧路径或占位）
 */

const LOGOS_BASE = 'images/models/logos'

// 模型 id -> logos 中的 basename（不含扩展名），与 logos 目录重命名结果一致
const MODEL_ID_TO_LOGO_BASENAME = {
  OPENAI: 'openai',
  OLLAMA: 'ollama',
  XINFERENCE: 'xinference',
  ONEAPI: 'oneapi',
  FASTCHAT: 'vllm',
  OPENAI_COMPATIBLE: 'api-compatible',
  DEEPSEEK: 'deepseek',
  GEMINI: 'gemini',
  ZHIPU: 'zhipu',
  BAIDU: 'baidu-ai',
  REPLICATE_FAL_AI: 'stability',
  openai: 'openai',
  ollama: 'ollama',
  nvidia: 'nvidia',
  grok: 'grok',
  hyperbolic: 'hyperbolic',
  mistral: 'mistral',
  jina: 'jina',
  perplexity: 'perplexity',
  modelscope: 'modelscope',
  'tianyi-xirang': 'xirang-B42-6Dao',
  'tencent-hunyuan': 'hunyuan',
  'tencent-cloud-ti': 'tencentcloud',
  'baidu-qianfan': 'qianfan',
  gpustack: 'gpustack-D7EptUU-',
  'voyage-ai': 'voyageai',
  'aws-bedrock': 'aws-bedrock',
  poe: 'poe',
  totoro: 'longcat_logo',
  huggingface: 'huggingface',
  'vercel-ai': 'google',
  cerebras: 'cerebras',
  'xiaomi-mimo': 'mimo',
  'new-api': 'newapi',
  'lm-studio': 'lmstudio',
  CherryIN: 'api-compatible',
  OPENAI_RESPONSE: 'openai',
  anthropic: 'claude',
  'azure-openai': 'openai',
  gemini: 'gemini',
  'vertex-ai': 'google',
  'github-models': 'github',
  'github-copilot': 'github-copilot',
  'lingyi-wanwu': 'yi',
  moonshot: 'moonshot',
  baichuan: 'baichuan',
  'aliyun-bailian': 'bailian',
  'step-ai': 'zero-one',
  volcengine: 'volcengine-la_PI8m-',
  'wuwen-xinqiong': 'ling',
  minimax: 'minimax-B0Eo-1V9',
  groq: 'groq',
  together: 'together',
  fireworks: 'fireworks',
  aihubmix: 'aihubmix',
  ocoolai: 'ocoolai',
  zhipu: 'zhipu',
  deepseek: 'deepseek',
  'alaya-new': 'alayanew',
  dmxapi: 'DMXAPI',
  aionly: 'aiOnly-CX5LzR-B',
  burncloud: 'burncloud',
  tokenflux: 'tokenflux',
  '302-ai': '302ai-OYnezl-B',
  cephalon: 'cephalon',
  lanyun: 'lanyun',
  ph8: 'ph8',
  sophnet: 'sophnet',
  ppio: 'ppio',
  qiniu: 'qiniu',
  openrouter: 'openrouter',
  // 察元AI助理 ribbon 模型选择：具体模型 id -> logos basename
  'gpt-4o': 'openai', 'gpt-4': 'openai', 'gpt-4-turbo': 'openai', 'gpt-3.5': 'openai',
  'claude-3.5': 'claude', 'claude-3': 'claude', claude: 'claude',
  'gemini-pro': 'gemini', gemini: 'gemini',
  'deepseek-v3': 'deepseek', 'deepseek-r1': 'deepseek', 'deepseek-coder': 'deepseek',
  doubao: 'doubao', 'doubao-pro': 'doubao',
  'qwen-max': 'qwen', 'qwen-plus': 'qwen', qwen: 'qwen',
  'wenxin-4': 'wenxin-PRX-yHSt', wenxin: 'wenxin-PRX-yHSt',
  'ernie-4.0-8k': 'qianfan', 'ernie-3.5-8k': 'qianfan', 'ernie-speed-128k': 'qianfan',
  'chatglm-4': 'zhipu', 'glm-4': 'zhipu',
  kimi: 'moonshot', moonshot: 'moonshot',
  'yi-large': 'yi', 'yi-medium': 'yi', yi: 'yi',
  ollama: 'ollama',
  baichuan: 'baichuan',
  'mistral-large': 'mistral', mixtral: 'mistral',
  'llama-3': 'llama',
  hunyuan: 'hunyuan',
  xinghuo: 'sparkdesk',
  minimax: 'minimax-B0Eo-1V9',
  step: 'zero-one',
  grok: 'grok',
  perplexity: 'perplexity',
  // 补充模型
  coze: 'coze',
  internlm: 'internlm',
  openrouter: 'openrouter',
  groq: 'groq',
  together: 'together',
  fireworks: 'fireworks',
  cohere: 'cohere',
  'netease-youdao': 'netease-youdao',
  pangu: 'pangu',
  sensetime: 'sensetime',
  hailuo: 'hailuo',
  o3: 'o3',
  'gpt_o1': 'gpt_o1',
  'gpt-5': 'gpt-5',
  'gpt-5.1': 'gpt-5.1-Cbwac6R-',
  xinference: 'xinference',
  oneapi: 'oneapi',
  vllm: 'vllm',
  'new-api': 'newapi',
  'lm-studio': 'lmstudio',
  'api-compatible': 'api-compatible',
  '360': '360-D7q-rf3l',
  '360智脑': '360-D7q-rf3l'
}

// 扩展名偏好（logos 中多为 png/webp/svg）
const EXT_ORDER = ['png', 'webp', 'svg']

/**
 * 根据模型 id 得到 logos 目录下的图标路径（优先 logos，无则回退占位）
 * @param {string} modelId - 模型 id（如 openai、tencent-hunyuan）
 * @returns {string} 相对路径，如 images/models/logos/openai.png
 */
export function getModelLogoPath(modelId) {
  if (!modelId) return ''
  const normalized = String(modelId).trim().toLowerCase().replace(/_/g, '-')
  // 察元桌面版镜像组(providerId 形如 CHAYUAN_DESKTOP::<group>)：本地组用本系统 logo(不在 logos 目录,直接返回)；
  // 云端平台组按平台名复用现有 logo 映射。
  if (normalized.startsWith('chayuan-desktop::')) {
    const platform = normalized.slice('chayuan-desktop::'.length)
    if (!platform || platform.startsWith('local')) return 'images/logo-avatar.png'
    return getModelLogoPath(platform)
  }
  let basename = MODEL_ID_TO_LOGO_BASENAME[modelId] ?? MODEL_ID_TO_LOGO_BASENAME[normalized]
  if (!basename) basename = normalized
  const ext = BASENAME_EXT[basename] || 'png'
  return `${LOGOS_BASE}/${basename}.${ext}`
}

// 部分 logo 为 webp/svg，与 logos 目录一致
const BASENAME_EXT = {
  aihubmix: 'webp', alayanew: 'webp', 'aws-bedrock': 'webp', 'baidu-ai': 'png', 'qianfan': 'svg', bailian: 'png',
  burncloud: 'png', cerebras: 'webp', coze: 'webp', duckduckgo: 'webp', gemini: 'png',
  'github-copilot': 'webp', huggingface: 'webp', lmstudio: 'png', mimo: 'svg', modelscope: 'png',
  moonshot: 'webp', newapi: 'png', ollama: 'png', openrouter: 'png', perplexity: 'png',
  voyageai: 'png', xirang: 'png', nvidia: 'png', deepseek: 'png', openai: 'png', groq: 'png',
  together: 'png', fireworks: 'png', anthropic: 'png', claude: 'png', qwen: 'png', yi: 'png',
  zhipu: 'png', hunyuan: 'png', ph8: 'png', lanyun: 'png', tokenflux: 'png', minimax: 'png',
  xinference: 'svg', oneapi: 'svg', vllm: 'svg', 'api-compatible': 'svg',
  'xirang-B42-6Dao': 'png', 'gpustack-D7EptUU-': 'svg', 'volcengine-la_PI8m-': 'png',
  tencentcloud: 'png', sophnet: 'png', ppio: 'png', qiniu: 'png', cephalon: 'svg',
  mistral: 'svg', jina: 'svg', baichuan: 'svg',
  'minimax-B0Eo-1V9': 'png', 'aiOnly-CX5LzR-B': 'webp', poe: 'svg',
  '302ai-OYnezl-B': 'webp', longcat_logo: 'png',
  'wenxin-PRX-yHSt': 'png', sparkdesk: 'png', 'zero-one': 'png', llama: 'png', doubao: 'png',
  coze: 'webp', internlm: 'png', cohere: 'png', 'netease-youdao': 'svg', pangu: 'svg',
  sensetime: 'png', hailuo: 'png', o3: 'png', 'gpt_o1': 'png', 'gpt-5': 'png',
  'gpt-5.1-Cbwac6R-': 'png',   '360-D7q-rf3l': 'png'
}

// 目录里实际存在的 logo basename 集合(构建期由目录清单生成;厂商自定义/运行期新增
// 的不在此列,走 <img> @error 兜底)。已知无 logo 的厂商直接渲染首字,不发 404 请求。
const KNOWN_LOGO_BASENAMES = new Set([
  "302ai-OYnezl-B",
  "360-D7q-rf3l",
  "360_dark-Cy",
  "3mintop",
  "DMXAPI",
  "DMXAPI-to-img",
  "Tesseract.js",
  "ai21",
  "aiOnly-CX5LzR-B",
  "aihubmix",
  "aimass",
  "aimass_dark-C4wmC-vb",
  "aisingapore",
  "aisingapore_dark",
  "aistudio",
  "alayanew",
  "anthropic",
  "api-compatible",
  "application",
  "avatar",
  "aws-bedrock",
  "baichuan",
  "baidu-ai",
  "baidu-ai-search",
  "bailian",
  "baixiaoying",
  "bigcode",
  "bigcode_dark",
  "bocha",
  "burncloud",
  "cephalon",
  "cerebras",
  "chatglm_dark",
  "cherry-text-logo",
  "cherryin",
  "cici",
  "claude",
  "claude_dark",
  "codegeex",
  "codegeex_dark",
  "cohere",
  "cohere_dark",
  "copilot",
  "copilot_dark",
  "coze",
  "dalle",
  "dalle_dark",
  "dbrx",
  "deepseek",
  "deepseek_dark",
  "dianxin",
  "dianxin_dark",
  "dmxapi-logo",
  "dmxapi-logo-dark",
  "doc2x",
  "doubao",
  "doubao-COZHhDj5",
  "doubao_dark",
  "duckduckgo",
  "embedding",
  "felo",
  "fireworks",
  "flux",
  "flux_dark",
  "gemini",
  "gemma",
  "gemma_dark",
  "gitee-ai",
  "github",
  "github-copilot",
  "google",
  "gpt-5",
  "gpt-5-chat",
  "gpt-5-codex",
  "gpt-5-mini",
  "gpt-5-nano",
  "gpt-5.1-Cbwac6R-",
  "gpt-5.1-chat",
  "gpt-5.1-codex",
  "gpt-5.1-codex-mini",
  "gpt_3.5",
  "gpt_4",
  "gpt_image_1",
  "gpt_o1",
  "gpustack-D7EptUU-",
  "grok",
  "grok-C9APDUTb",
  "grok-x",
  "grok_dark",
  "groq",
  "gryphe",
  "gryphe_dark-Du2H-Bxr",
  "hailuo",
  "hailuo_dark",
  "huggingface",
  "huggingface-YbP47-Zd",
  "huggingface_dark",
  "hunyuan",
  "hunyuan_dark",
  "hyperbolic",
  "internlm",
  "internlm_dark",
  "internvl",
  "jina",
  "keling-DW",
  "keling_dark",
  "lanyun",
  "ling",
  "llama",
  "llama_dark",
  "llava",
  "llava_dark",
  "lmstudio",
  "logo",
  "longcat_logo",
  "luma",
  "luma_dark",
  "magic",
  "magic_dark",
  "mediatek",
  "midjourney",
  "midjourney_dark",
  "mimo",
  "minimax-B0Eo-1V9",
  "minimax_dark",
  "mistral",
  "modelscope",
  "monica",
  "moonshot",
  "netease-youdao",
  "newapi",
  "nousresearch",
  "nvidia",
  "nvidia_dark",
  "o3",
  "ocoolai",
  "ollama",
  "oneapi",
  "openai",
  "openrouter",
  "paddleocr",
  "palm",
  "palm_dark",
  "pangu",
  "perplexity",
  "ph8",
  "poe",
  "ppio",
  "qianfan",
  "qiniu",
  "qwen",
  "qwen_dark",
  "rakutenai",
  "rakutenai_dark",
  "sensetime",
  "sophnet",
  "sparkdesk",
  "sparkdesk_dark",
  "stability",
  "stability_dark",
  "tavily",
  "tele",
  "tele_dark",
  "tencentcloud",
  "thinkany",
  "together",
  "tokenflux",
  "vidu",
  "vidu_dark",
  "vllm",
  "volcengine-la_PI8m-",
  "voyageai",
  "wenxin-PRX-yHSt",
  "wenxin_dark",
  "wpslingxi",
  "xiaoyi",
  "xinference",
  "xirang-B42-6Dao",
  "xirang_dark",
  "yi",
  "yi_dark",
  "zai-D",
  "zero-one",
  "zhihu",
  "zhipu"
])

/**
 * 该 provider 是否有已知可用的 logo 文件。
 * 不在映射表且名字未收录 → 视为无 logo(调用方直接显示首字,不发 img 请求)。
 */
export function hasKnownModelLogo(modelId) {
  if (!modelId) return false
  const normalized = String(modelId).trim().toLowerCase().replace(/_/g, '-')
  if (normalized.startsWith('chayuan-desktop::')) {
    return hasKnownModelLogo(normalized.slice('chayuan-desktop::'.length))
  }
  const basename = MODEL_ID_TO_LOGO_BASENAME[modelId] ?? MODEL_ID_TO_LOGO_BASENAME[normalized]
  if (basename) return true
  return KNOWN_LOGO_BASENAMES.has(normalized)
}
