// 自动生成,请勿手工编辑 —— 运行 scripts/gen-assistant-domain-manifest.mjs 重生成。
// 领域 -> {中文名, 助手数, 所属 pack 短键[]};供对话窗口 group-first 懒加载只渲分组+计数。
export const ASSISTANT_TOTAL = 4526
export const DOMAIN_COUNT = 228
export const DOMAIN_ORDER = ["catering", "crossborder", "defmob", "ecommerce", "film", "gov", "govdoc", "govemergency", "govparty", "govsupervise", "homeservice", "landscape", "logistics", "marketing", "mildoc", "millogistics", "procurator", "service", "studyabroad", "teaart", "travel", "water", "webnovel", "academic", "advertising", "appliancerepair", "aviation", "beverage", "cultural", "education", "fashion", "illustration", "instrumentedu", "judicial", "moving", "music", "realestate", "recycling", "survey", "telecom", "veteran", "veterinary", "banking", "bidding", "carwash", "chemical", "data", "dentistry", "eldercare", "finance", "floral", "franchise", "goveconomy", "govgrassroots", "govpeople", "greenplant", "homedecor", "ip", "justice", "legal", "localfood", "manufacturing", "maternal", "media", "medical", "milpolitical", "miltraining", "nonprofit", "parenting", "personal", "pharmacy", "photography", "podcast", "police", "printing", "psychology", "recruit", "secrecy", "security", "shortdrama", "sports", "tea", "tech", "ticketing", "trade", "tutoring", "verify", "wedding", "agriculture", "aquatic", "automotive", "bakery", "cbexpress", "community", "court", "customs", "drivingschool", "elearning", "energy", "foreign", "govenviron", "govmeeting", "govpersonnel", "govpolicy", "govservice", "govstats", "hr", "insurance", "library", "liquor", "mcn", "milequip", "milpersonnel", "milsafety", "publishing", "salon", "tcmclinic", "translation", "wellness", "beauty", "carrental", "construction", "consulting", "eduadmin", "examprep", "funeral", "govindustryit", "govmarketreg", "govorg", "govpetition", "jewelry", "kb-verify", "milparty", "museum", "notary", "optical", "organizing", "partyschool", "pet", "prison", "school", "steel", "textile", "tradeassoc", "womensfed", "arbitration", "cyleague", "docutil", "govdevreform", "govdiscipline", "govforestry", "govnatres", "hotel", "hrservice", "preschool", "railway", "rehabilitation", "specialedu", "union", "accounting", "arttraining", "buildmaterial", "cdc", "costengineer", "exhibition", "fitness", "foodprocess", "fresh", "govaudit", "govcivil", "govcommerce", "govcultour", "govfinance", "govhealth", "govhotline", "govhousing", "govhrss", "govtax", "govtransport", "govwater", "industrialpark", "livestock", "medbeauty", "meddevice", "property", "safetyprod", "securities", "taxagent", "university", "voccollege", "assetappraisal", "auction", "disabledfed", "examboard", "forensic", "furniture", "govagrirural", "govarchive", "govmedicare", "govpublicity", "govservicehall", "govstaffing", "govunitedfront", "govurbanmgmt", "govreview", "aesthetic", "antique", "ballsport", "bonsai", "calligraphy", "climbing", "coin", "companion", "confinement", "escaperoom", "figurine", "funeralpet", "gaming", "hanfu", "incense", "jade", "koi", "matchmaking", "mounting", "pottery", "redwood", "scriptmurder", "seal"]
export const DOMAIN_MANIFEST = {
  "catering": { label: "餐饮 / 食品", count: 24, packs: ["Catering", "CateringExt"] },
  "crossborder": { label: "跨境电商", count: 24, packs: ["Crossborder", "CrossborderExt"] },
  "defmob": { label: "国防动员 / 人防", count: 24, packs: ["DefMob", "DefMobExt"] },
  "ecommerce": { label: "电商 / 零售", count: 24, packs: ["Ecommerce", "EcommerceExt"] },
  "film": { label: "影视 / 编剧", count: 24, packs: ["Film", "FilmExt"] },
  "gov": { label: "政务 / 公文", count: 24, packs: ["Gov", "GovExt"] },
  "govdoc": { label: "法定公文", count: 24, packs: ["GovDoc", "GovDocExt"] },
  "govemergency": { label: "应急/舆情", count: 24, packs: ["GovEmergency", "GovEmergencyExt"] },
  "govparty": { label: "党建/党务", count: 24, packs: ["GovParty", "GovPartyExt"] },
  "govsupervise": { label: "督查/考核", count: 24, packs: ["GovSupervise", "GovSuperviseExt"] },
  "homeservice": { label: "家政 / 生活服务", count: 24, packs: ["HomeService", "HomeServiceExt"] },
  "landscape": { label: "园林 / 景观", count: 24, packs: ["Landscape", "LandscapeExt"] },
  "logistics": { label: "物流 / 供应链", count: 24, packs: ["Logistics", "LogisticsExt"] },
  "marketing": { label: "市场营销", count: 24, packs: ["Marketing", "MarketingExt"] },
  "mildoc": { label: "军事公文文电", count: 24, packs: ["MilDoc", "MilDocExt"] },
  "millogistics": { label: "后勤保障", count: 24, packs: ["MilLogistics", "MilLogisticsExt"] },
  "procurator": { label: "检察", count: 24, packs: ["Procurator"] },
  "service": { label: "客服 / 沟通", count: 24, packs: ["Service", "ServiceExt"] },
  "studyabroad": { label: "留学 / 移民", count: 24, packs: ["StudyAbroad", "StudyAbroadExt"] },
  "teaart": { label: "茶艺", count: 24, packs: ["TeaArt", "TeaArtExt"] },
  "travel": { label: "旅游 / 酒店", count: 24, packs: ["Travel", "TravelExt"] },
  "water": { label: "水利 / 水电", count: 24, packs: ["Water", "WaterExt"] },
  "webnovel": { label: "网文 / 小说", count: 24, packs: ["Webnovel", "WebnovelExt"] },
  "academic": { label: "高校 / 科研", count: 23, packs: ["Academic", "AcademicExt"] },
  "advertising": { label: "广告 / 公关会展", count: 23, packs: ["Advertising", "AdvertisingExt"] },
  "appliancerepair": { label: "家电维修", count: 23, packs: ["ApplianceRepair", "ApplianceRepairExt"] },
  "aviation": { label: "民航", count: 23, packs: ["Aviation"] },
  "beverage": { label: "茶饮 / 咖啡", count: 23, packs: ["Beverage", "BeverageExt"] },
  "cultural": { label: "文创 / 非遗", count: 23, packs: ["Cultural", "CulturalExt"] },
  "education": { label: "教育 / 教学", count: 23, packs: ["Education", "EducationExt"] },
  "fashion": { label: "服装 / 时尚", count: 23, packs: ["Fashion", "FashionExt"] },
  "illustration": { label: "插画 / 设计", count: 23, packs: ["Illustration", "IllustrationExt"] },
  "instrumentedu": { label: "乐器教育", count: 23, packs: ["InstrumentEdu", "InstrumentEduExt"] },
  "judicial": { label: "法律 / 司法", count: 23, packs: ["Judicial", "JudicialExt"] },
  "moving": { label: "搬家 / 货运", count: 23, packs: ["Moving", "MovingExt"] },
  "music": { label: "音乐 / 词曲", count: 23, packs: ["Music", "MusicExt"] },
  "realestate": { label: "房产 / 物业", count: 23, packs: ["RealEstate", "RealEstateExt"] },
  "recycling": { label: "二手回收", count: 23, packs: ["Recycling", "RecyclingExt"] },
  "survey": { label: "测绘 / 地理", count: 23, packs: ["Survey", "SurveyExt"] },
  "telecom": { label: "电信 / 通信", count: 23, packs: ["Telecom", "TelecomExt"] },
  "veteran": { label: "退役军人事务", count: 23, packs: ["Veteran", "VeteranExt"] },
  "veterinary": { label: "宠物医疗", count: 23, packs: ["Veterinary", "VeterinaryExt"] },
  "banking": { label: "金融 / 投融资", count: 22, packs: ["Banking", "BankingExt"] },
  "bidding": { label: "招投标", count: 22, packs: ["Bidding", "BiddingExt"] },
  "carwash": { label: "洗车 / 美容", count: 22, packs: ["CarWash", "CarWashExt"] },
  "chemical": { label: "化工 / 材料", count: 22, packs: ["Chemical", "ChemicalExt"] },
  "data": { label: "数据 / 报表", count: 22, packs: ["Data", "DataExt"] },
  "dentistry": { label: "口腔/牙科", count: 22, packs: ["Dentistry", "DentistryExt"] },
  "eldercare": { label: "养老 / 老年服务", count: 22, packs: ["Eldercare", "EldercareExt"] },
  "finance": { label: "财务 / 会计", count: 22, packs: ["Finance", "FinanceExt"] },
  "floral": { label: "花艺 / 鲜花", count: 22, packs: ["Floral", "FloralExt"] },
  "franchise": { label: "招商加盟", count: 22, packs: ["Franchise", "FranchiseExt"] },
  "goveconomy": { label: "经济/营商", count: 22, packs: ["GovEconomy", "GovEconomyExt"] },
  "govgrassroots": { label: "基层治理", count: 22, packs: ["GovGrassroots", "GovGrassrootsExt"] },
  "govpeople": { label: "政协人大/统战", count: 22, packs: ["GovPeople", "GovPeopleExt"] },
  "greenplant": { label: "绿植 / 园艺", count: 22, packs: ["GreenPlant", "GreenPlantExt"] },
  "homedecor": { label: "家居 / 建材", count: 22, packs: ["HomeDecor", "HomeDecorExt"] },
  "ip": { label: "知识产权", count: 22, packs: ["Ip", "IpExt"] },
  "justice": { label: "司法行政", count: 22, packs: ["Justice"] },
  "legal": { label: "合同 / 法务", count: 22, packs: ["Legal", "LegalExt"] },
  "localfood": { label: "土特产/食品礼盒", count: 22, packs: ["LocalFood", "LocalFoodExt"] },
  "manufacturing": { label: "制造 / 工程", count: 22, packs: ["Manufacturing", "ManufacturingExt"] },
  "maternal": { label: "母婴 / 育儿", count: 22, packs: ["Maternal", "MaternalExt"] },
  "media": { label: "媒体 / 新闻", count: 22, packs: ["Media", "MediaExt"] },
  "medical": { label: "医疗 / 医学", count: 22, packs: ["Medical", "MedicalExt"] },
  "milpolitical": { label: "政治工作", count: 22, packs: ["MilPolitical", "MilPoliticalExt"] },
  "miltraining": { label: "训练管理", count: 22, packs: ["MilTraining", "MilTrainingExt"] },
  "nonprofit": { label: "公益 / 社工", count: 22, packs: ["Nonprofit", "NonprofitExt"] },
  "parenting": { label: "家庭教育", count: 22, packs: ["Parenting", "ParentingExt"] },
  "personal": { label: "个人 / 生活", count: 22, packs: ["Personal", "PersonalExt"] },
  "pharmacy": { label: "药店 / 药房", count: 22, packs: ["Pharmacy", "PharmacyExt"] },
  "photography": { label: "摄影 / 写真", count: 22, packs: ["Photography", "PhotographyExt"] },
  "podcast": { label: "播客 / 音频", count: 22, packs: ["Podcast", "PodcastExt"] },
  "police": { label: "公安 / 治安", count: 22, packs: ["Police", "PoliceExt"] },
  "printing": { label: "印刷 / 包装", count: 22, packs: ["Printing", "PrintingExt"] },
  "psychology": { label: "心理咨询", count: 22, packs: ["Psychology", "PsychologyExt"] },
  "recruit": { label: "招聘 / 猎头", count: 22, packs: ["Recruit", "RecruitExt"] },
  "secrecy": { label: "保密合规自查（离线）", count: 22, packs: ["Secrecy", "SecrecyExt"] },
  "security": { label: "安防 / 安保", count: 22, packs: ["Security", "SecurityExt"] },
  "shortdrama": { label: "短剧 / 微短剧", count: 22, packs: ["ShortDrama", "ShortDramaExt"] },
  "sports": { label: "体育 / 健身", count: 22, packs: ["Sports", "SportsExt"] },
  "tea": { label: "茶叶", count: 22, packs: ["Tea", "TeaExt"] },
  "tech": { label: "IT / 技术", count: 22, packs: ["Tech", "TechExt"] },
  "ticketing": { label: "票务 / 演出", count: 22, packs: ["Ticketing", "TicketingExt"] },
  "trade": { label: "外贸 / 跨境", count: 22, packs: ["Trade", "TradeExt"] },
  "tutoring": { label: "家教/一对一", count: 22, packs: ["Tutoring", "TutoringExt"] },
  "verify": { label: "文档核对", count: 22, packs: ["Audit", "AuditExt"] },
  "wedding": { label: "婚庆 / 活动", count: 22, packs: ["Wedding", "WeddingExt"] },
  "agriculture": { label: "农林牧渔", count: 21, packs: ["Agriculture", "AgricultureExt"] },
  "aquatic": { label: "游泳 / 水上", count: 21, packs: ["Aquatic", "AquaticExt"] },
  "automotive": { label: "汽车 / 交通", count: 21, packs: ["Automotive", "AutomotiveExt"] },
  "bakery": { label: "烘焙 / 甜品", count: 21, packs: ["Bakery", "BakeryExt"] },
  "cbexpress": { label: "跨境物流", count: 21, packs: ["CbExpress", "CbExpressExt"] },
  "community": { label: "社区 / 社工", count: 21, packs: ["Community", "CommunityExt"] },
  "court": { label: "法院 / 审判", count: 21, packs: ["Court", "CourtExt"] },
  "customs": { label: "海关 / 口岸", count: 21, packs: ["Customs"] },
  "drivingschool": { label: "驾校 / 驾培", count: 21, packs: ["DrivingSchool", "DrivingSchoolExt"] },
  "elearning": { label: "在线教育", count: 21, packs: ["Elearning", "ElearningExt"] },
  "energy": { label: "能源 / 环保", count: 21, packs: ["Energy", "EnergyExt"] },
  "foreign": { label: "外事 / 外交", count: 21, packs: ["Foreign"] },
  "govenviron": { label: "生态环境", count: 21, packs: ["GovEnviron"] },
  "govmeeting": { label: "会务/综合", count: 21, packs: ["GovMeeting", "GovMeetingExt"] },
  "govpersonnel": { label: "干部/人事", count: 21, packs: ["GovPersonnel", "GovPersonnelExt"] },
  "govpolicy": { label: "政策法规", count: 21, packs: ["GovPolicy", "GovPolicyExt"] },
  "govservice": { label: "政务服务", count: 21, packs: ["GovService", "GovServiceExt"] },
  "govstats": { label: "统计", count: 21, packs: ["GovStats"] },
  "hr": { label: "人力资源", count: 21, packs: ["Hr", "HrExt"] },
  "insurance": { label: "保险", count: 21, packs: ["Insurance", "InsuranceExt"] },
  "library": { label: "图书馆", count: 21, packs: ["Library"] },
  "liquor": { label: "酒水", count: 21, packs: ["Liquor", "LiquorExt"] },
  "mcn": { label: "MCN / 直播", count: 21, packs: ["Mcn", "McnExt"] },
  "milequip": { label: "装备管理", count: 21, packs: ["MilEquip", "MilEquipExt"] },
  "milpersonnel": { label: "人事兵员", count: 21, packs: ["MilPersonnel", "MilPersonnelExt"] },
  "milsafety": { label: "安全保密", count: 21, packs: ["MilSafety", "MilSafetyExt"] },
  "publishing": { label: "出版 / 校对", count: 21, packs: ["Publishing", "PublishingExt"] },
  "salon": { label: "美容美发", count: 21, packs: ["Salon", "SalonExt"] },
  "tcmclinic": { label: "中医理疗", count: 21, packs: ["TcmClinic", "TcmClinicExt"] },
  "translation": { label: "翻译 / 本地化", count: 21, packs: ["Translation", "TranslationExt"] },
  "wellness": { label: "健康养生", count: 21, packs: ["Wellness", "WellnessExt"] },
  "beauty": { label: "美妆 / 日化", count: 20, packs: ["Beauty", "BeautyExt"] },
  "carrental": { label: "租车", count: 20, packs: ["CarRental", "CarRentalExt"] },
  "construction": { label: "建筑施工", count: 20, packs: ["Construction"] },
  "consulting": { label: "管理咨询", count: 20, packs: ["Consulting"] },
  "eduadmin": { label: "教育行政", count: 20, packs: ["EduAdmin"] },
  "examprep": { label: "考公考研培训", count: 20, packs: ["ExamPrep", "ExamPrepExt"] },
  "funeral": { label: "殡葬服务", count: 20, packs: ["Funeral", "FuneralExt"] },
  "govindustryit": { label: "工业和信息化", count: 20, packs: ["GovIndustryIt"] },
  "govmarketreg": { label: "市场监管", count: 20, packs: ["GovMarketReg"] },
  "govorg": { label: "组织部", count: 20, packs: ["GovOrg"] },
  "govpetition": { label: "信访/民生", count: 20, packs: ["GovPetition", "GovPetitionExt"] },
  "jewelry": { label: "珠宝 / 钟表", count: 20, packs: ["Jewelry", "JewelryExt"] },
  "kb-verify": { label: "知识库对比", count: 20, packs: ["KbVerify", "KbVerifyExt"] },
  "milparty": { label: "党务纪检", count: 20, packs: ["MilParty", "MilPartyExt"] },
  "museum": { label: "博物馆", count: 20, packs: ["Museum"] },
  "notary": { label: "公证", count: 20, packs: ["Notary"] },
  "optical": { label: "眼镜 / 视光", count: 20, packs: ["Optical", "OpticalExt"] },
  "organizing": { label: "收纳整理", count: 20, packs: ["Organizing", "OrganizingExt"] },
  "partyschool": { label: "党校", count: 20, packs: ["PartySchool"] },
  "pet": { label: "宠物", count: 20, packs: ["Pet", "PetExt"] },
  "prison": { label: "监狱 / 戒毒", count: 20, packs: ["Prison"] },
  "school": { label: "学校管理", count: 20, packs: ["School"] },
  "steel": { label: "钢铁冶金", count: 20, packs: ["Steel"] },
  "textile": { label: "纺织服装", count: 20, packs: ["Textile"] },
  "tradeassoc": { label: "行业协会 / 商会", count: 20, packs: ["TradeAssoc"] },
  "womensfed": { label: "妇联", count: 20, packs: ["WomensFed"] },
  "arbitration": { label: "仲裁", count: 19, packs: ["Arbitration"] },
  "cyleague": { label: "共青团", count: 19, packs: ["CyLeague"] },
  "docutil": { label: "通用文档工具", count: 19, packs: ["DocUtil"] },
  "govdevreform": { label: "发展改革", count: 19, packs: ["GovDevReform"] },
  "govdiscipline": { label: "纪检监察", count: 19, packs: ["GovDiscipline"] },
  "govforestry": { label: "林业草原", count: 19, packs: ["GovForestry"] },
  "govnatres": { label: "自然资源 / 规划", count: 19, packs: ["GovNatRes"] },
  "hotel": { label: "酒店", count: 19, packs: ["Hotel"] },
  "hrservice": { label: "人力资源服务", count: 19, packs: ["HrService"] },
  "preschool": { label: "学前教育", count: 19, packs: ["Preschool"] },
  "railway": { label: "铁路", count: 19, packs: ["Railway"] },
  "rehabilitation": { label: "康复医疗", count: 19, packs: ["Rehabilitation"] },
  "specialedu": { label: "特殊教育", count: 19, packs: ["SpecialEdu"] },
  "union": { label: "工会", count: 19, packs: ["Union"] },
  "accounting": { label: "会计事务所", count: 18, packs: ["Accounting"] },
  "arttraining": { label: "美术培训", count: 18, packs: ["ArtTraining"] },
  "buildmaterial": { label: "建材", count: 18, packs: ["BuildMaterial"] },
  "cdc": { label: "疾控", count: 18, packs: ["Cdc"] },
  "costengineer": { label: "工程造价", count: 18, packs: ["CostEngineer"] },
  "exhibition": { label: "会展", count: 18, packs: ["Exhibition"] },
  "fitness": { label: "健身", count: 18, packs: ["Fitness"] },
  "foodprocess": { label: "食品生产加工", count: 18, packs: ["FoodProcess"] },
  "fresh": { label: "生鲜零售", count: 18, packs: ["Fresh"] },
  "govaudit": { label: "审计机关", count: 18, packs: ["GovAudit"] },
  "govcivil": { label: "民政", count: 18, packs: ["GovCivil"] },
  "govcommerce": { label: "商务", count: 18, packs: ["GovCommerce"] },
  "govcultour": { label: "文旅", count: 18, packs: ["GovCulTour"] },
  "govfinance": { label: "财政", count: 18, packs: ["GovFinance"] },
  "govhealth": { label: "卫生健康", count: 18, packs: ["GovHealth"] },
  "govhotline": { label: "12345 热线", count: 18, packs: ["GovHotline"] },
  "govhousing": { label: "住建", count: 18, packs: ["GovHousing"] },
  "govhrss": { label: "人力资源社会保障", count: 18, packs: ["GovHrss"] },
  "govtax": { label: "税务", count: 18, packs: ["GovTax"] },
  "govtransport": { label: "交通运输", count: 18, packs: ["GovTransport"] },
  "govwater": { label: "水利 / 水务", count: 18, packs: ["GovWater"] },
  "industrialpark": { label: "园区运营", count: 18, packs: ["IndustrialPark"] },
  "livestock": { label: "畜牧养殖", count: 18, packs: ["Livestock"] },
  "medbeauty": { label: "医疗美容", count: 18, packs: ["MedBeauty"] },
  "meddevice": { label: "医疗器械", count: 18, packs: ["MedDevice"] },
  "property": { label: "物业管理", count: 18, packs: ["Property"] },
  "safetyprod": { label: "安全生产", count: 18, packs: ["SafetyProd"] },
  "securities": { label: "证券 / 基金", count: 18, packs: ["Securities"] },
  "taxagent": { label: "代理记账", count: 18, packs: ["TaxAgent"] },
  "university": { label: "高校行政", count: 18, packs: ["University"] },
  "voccollege": { label: "职业院校", count: 18, packs: ["VocCollege"] },
  "assetappraisal": { label: "资产评估", count: 17, packs: ["AssetAppraisal"] },
  "auction": { label: "拍卖", count: 17, packs: ["Auction"] },
  "disabledfed": { label: "残联", count: 17, packs: ["DisabledFed"] },
  "examboard": { label: "招生考试", count: 17, packs: ["ExamBoard"] },
  "forensic": { label: "司法鉴定", count: 17, packs: ["Forensic"] },
  "furniture": { label: "家具", count: 17, packs: ["Furniture"] },
  "govagrirural": { label: "农业农村", count: 17, packs: ["GovAgriRural"] },
  "govarchive": { label: "档案", count: 17, packs: ["GovArchive"] },
  "govmedicare": { label: "医保", count: 17, packs: ["GovMedicare"] },
  "govpublicity": { label: "宣传部", count: 17, packs: ["GovPublicity"] },
  "govservicehall": { label: "政务服务大厅", count: 17, packs: ["GovServiceHall"] },
  "govstaffing": { label: "机构编制", count: 17, packs: ["GovStaffing"] },
  "govunitedfront": { label: "统战 / 民宗", count: 17, packs: ["GovUnitedFront"] },
  "govurbanmgmt": { label: "城管执法", count: 17, packs: ["GovUrbanMgmt"] },
  "govreview": { label: "政务公文审查", count: 16, packs: ["GovReview"] },
  "aesthetic": { label: "美业 / 医美", count: 12, packs: ["Aesthetic"] },
  "antique": { label: "古玩 / 收藏", count: 12, packs: ["Antique"] },
  "ballsport": { label: "球类运动馆", count: 12, packs: ["BallSport"] },
  "bonsai": { label: "盆景/根雕", count: 12, packs: ["Bonsai"] },
  "calligraphy": { label: "书法 / 国画", count: 12, packs: ["Calligraphy"] },
  "climbing": { label: "攀岩/极限运动", count: 12, packs: ["Climbing"] },
  "coin": { label: "钱币/邮票", count: 12, packs: ["Coin"] },
  "companion": { label: "陪诊/陪护", count: 12, packs: ["Companion"] },
  "confinement": { label: "月子 / 母婴护理", count: 12, packs: ["Confinement"] },
  "escaperoom": { label: "密室逃脱", count: 12, packs: ["EscapeRoom"] },
  "figurine": { label: "手办 / 潮玩", count: 12, packs: ["Figurine"] },
  "funeralpet": { label: "宠物殡葬", count: 12, packs: ["FuneralPet"] },
  "gaming": { label: "游戏", count: 12, packs: ["Gaming"] },
  "hanfu": { label: "汉服 / 古风", count: 12, packs: ["Hanfu"] },
  "incense": { label: "香道/沉香", count: 12, packs: ["Incense"] },
  "jade": { label: "玉石/翡翠", count: 12, packs: ["Jade"] },
  "koi": { label: "观赏鱼/锦鲤", count: 12, packs: ["Koi"] },
  "matchmaking": { label: "婚恋 / 相亲", count: 12, packs: ["Matchmaking"] },
  "mounting": { label: "字画装裱", count: 12, packs: ["Mounting"] },
  "pottery": { label: "陶艺 / 手作", count: 12, packs: ["Pottery"] },
  "redwood": { label: "红木家具", count: 12, packs: ["Redwood"] },
  "scriptmurder": { label: "剧本杀", count: 12, packs: ["ScriptMurder"] },
  "seal": { label: "篆刻/印章", count: 12, packs: ["Seal"] },
}
