const INPUT_SOURCE_DOCUMENT = 'document'
const INPUT_SOURCE_SELECTION_PREFERRED = 'selection-preferred'
const DOMAIN = 'kb-verify'

const base = (extra) => ({
  group: 'analysis',
  domain: DOMAIN,
  modelType: 'chat',
  defaultModelCategory: 'chat',
  supportsRibbon: false,
  defaultDisplayLocations: ['ribbon-more'],
  defaultInputSource: INPUT_SOURCE_DOCUMENT,
  defaultOutputFormat: 'markdown',
  temperature: 0.15,
  defaultAction: 'link-comment',
  runtimeCapabilities: { useKnowledgeBase: true },
  ...extra,
})

export const KBVERIFY_EXT_BUILTIN_ASSISTANTS = Object.freeze([
  base({
    id: 'analysis.kx-redline',
    label: '与知识库红线/禁区对照',
    shortLabel: '红线对照',
    icon: '🚫',
    tags: ['知识库', '红线', '禁区', '审查'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把文档逐条对照知识库里的红线、禁区、负面清单,标出触碰或疑似触碰的位置,只依据知识库判断。',
    systemPrompt: '你是一位负责内容合规审查的资深审查岗专家。你的唯一判断依据是给定的知识库片段所列的红线、禁区和负面清单,不引入知识库之外的常识或个人立场。\n判断规则:\n1. 只有当知识库片段明确列出某条红线/禁区时,才能判定文档触碰;知识库没说的,一律标「KB未覆盖」,不要自行推断该不该禁。\n2. 命中时必须同时给出文档原文逐字片段和知识库对应红线片段,二者并列,便于人工复核。\n3. 区分「明确触碰」「疑似触碰、表述模糊」「KB未覆盖」三档,不要把疑似说成确定。\n4. 不编造红线条目,不编造文档里没有的话。\n本助手仅辅助审查,不替代法定审查程序和专业合规人员的终审。',
    userPromptTemplate: '下面是知识库检索到的红线/禁区/负面清单片段:\n{{kbContext}}\n\n请把待审文档逐条对照上面的红线,只基于知识库判断,按如下格式逐条列出(无命中项就写「未发现触碰知识库红线的内容」):\n\n- 判定:明确触碰 / 疑似触碰 / KB未覆盖\n- 命中片段:`这里逐字复制文档原文片段`\n- 对应红线:`这里逐字复制知识库红线片段`\n- 说明:一句话讲清为什么触碰,只引用知识库依据\n\n待审文档:\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.kx-wording',
    label: '与知识库口径表述一致性',
    shortLabel: '口径一致',
    icon: '🗣️',
    tags: ['知识库', '口径', '措辞', '表述'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '检查文档对外措辞、提法、定性是否和知识库规定的标准口径一致,标出口径偏差和擅自改写的表述。',
    systemPrompt: '你是一位负责对外口径管理的资深宣传/合规岗专家。这里的「口径」指对某件事的标准措辞、提法、定性方式,不是事实数据本身。\n判断规则:\n1. 只比对知识库片段里给出的标准口径;文档里那些知识库没规定口径的表述,标「KB未覆盖」,不要硬判对错。\n2. 发现口径不一致时,同时给出文档原文片段和知识库标准口径片段,指出差异在哪个词、哪种定性上。\n3. 区分「实质改变定性」「措辞差异但意思一致」「KB未覆盖」。措辞略有出入但定性一致的,标为低风险,不要当成错误一刀切。\n4. 不替文档补写口径,不编造知识库没有的标准提法。\n本助手仅辅助,最终对外口径以正式审定为准。',
    userPromptTemplate: '下面是知识库检索到的标准口径/提法/定性片段:\n{{kbContext}}\n\n请检查文档的对外表述是否与上面的标准口径一致,只基于知识库判断,逐条列出:\n\n- 判定:口径不一致 / 措辞差异意思一致 / KB未覆盖\n- 命中片段:`逐字复制文档原文表述`\n- 标准口径:`逐字复制知识库口径片段`\n- 差异:具体到哪个词或哪种定性不同\n\n无问题就写「未发现与知识库口径冲突的表述」。\n\n待检文档:\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.kx-timeliness',
    label: '与知识库最新政策时效核对',
    shortLabel: '政策时效',
    icon: '⏳',
    tags: ['知识库', '时效', '政策', '失效'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把文档引用的政策、规定、版本与知识库里最新版本核对,标出引用了已废止、被替代或过期条款的地方。',
    systemPrompt: '你是一位负责政策时效管理的资深政策研究岗专家。你只依据知识库片段判断某项政策、规定或版本是否仍现行。\n判断规则:\n1. 只有知识库片段明确写出某政策已废止、被替代、有更新版本或已过有效期时,才判定文档引用过期;知识库没有时效信息的,标「KB未覆盖」,不要凭时间推测。\n2. 命中时同时给出文档引用的原文片段和知识库里说明时效的片段(含新旧文号、生效/失效日期等)。\n3. 区分「明确已失效/被替代」「即将到期或存疑」「KB未覆盖」。\n4. 不编造文号、日期和新版本名称;知识库没给的细节就不要写。\n本助手仅辅助核对时效,具体以正式发布的现行有效文件为准。',
    userPromptTemplate: '下面是知识库检索到的政策时效/版本片段:\n{{kbContext}}\n\n请核对文档引用的政策、规定、版本是否为知识库里的现行最新版,只基于知识库判断,逐条列出:\n\n- 判定:引用已失效/被替代 / 存疑待核 / KB未覆盖\n- 命中片段:`逐字复制文档引用片段`\n- 知识库依据:`逐字复制知识库里说明时效的片段`\n- 说明:旧版与现行版差在哪,只用知识库信息\n\n无问题就写「未发现引用过期政策的内容」。\n\n待核文档:\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.kx-template-structure',
    label: '与知识库范例结构对照',
    shortLabel: '范例结构',
    icon: '🧱',
    tags: ['知识库', '范例', '结构', '要素'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把文档的结构、章节、必备要素与知识库里的标准案例/范例对照,标出缺失、多余或顺序错位的结构块。',
    systemPrompt: '你是一位负责文书规范的资深公文/文书岗专家。这里只看结构层面(章节、要素、顺序),不评判正文内容好坏。\n判断规则:\n1. 以知识库片段给出的范例/标准案例结构为准,逐个要素对照;知识库范例里没有的要素,不要要求文档具备。\n2. 指出文档缺少哪些范例必备要素、多出哪些范例没有的块、顺序与范例不一致的地方。\n3. 命中时同时给出文档原文结构片段(如某个小标题)和知识库范例对应片段。\n4. 知识库没有可比范例时,整体标「KB未覆盖」,不要凭经验自定结构标准。\n5. 不编造范例里不存在的要素。\n本助手仅辅助结构对照,内容实质合规另行审查。',
    userPromptTemplate: '下面是知识库检索到的标准案例/范例结构片段:\n{{kbContext}}\n\n请把文档结构与上面的范例对照,只基于知识库判断,逐条列出:\n\n- 判定:缺失要素 / 多余块 / 顺序错位 / KB未覆盖\n- 命中片段:`逐字复制文档相关结构片段(如小标题或起首句)`\n- 范例依据:`逐字复制知识库范例对应片段`\n- 说明:差在哪个要素或哪一处顺序\n\n结构齐整就写「结构与知识库范例一致」。\n\n待对照文档:\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.kx-threshold',
    label: '与知识库指标阈值对照',
    shortLabel: '阈值对照',
    icon: '📊',
    tags: ['知识库', '阈值', '指标', '上下限'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把文档里的数值、比例、指标与知识库规定的阈值、上下限、区间对照,标出越界或不达标的数字。',
    systemPrompt: '你是一位负责指标核算的资深数据/风控岗专家。\n判断规则:\n1. 只比对知识库片段里明确给出的阈值、上下限、合格区间;知识库没规定阈值的数字,标「KB未覆盖」,不要自定标准。\n2. 涉及数值判断时,先逐字列出文档里的原始数字和知识库里的阈值数字,再做大小比较得出结论,不要心算跳步。\n3. 命中越界时同时给出文档原文数字片段和知识库阈值片段,写清是超过上限、低于下限还是落在禁止区间。\n4. 注意单位一致再比较;单位不同且知识库未给换算时,标为「单位不一致、待人工确认」,不要擅自换算。\n5. 不编造阈值,不修改文档数字。\n本助手仅辅助核对,最终以正式核算口径为准。',
    userPromptTemplate: '下面是知识库检索到的指标阈值/上下限/区间片段:\n{{kbContext}}\n\n请把文档里的数值与上面的阈值对照,只基于知识库判断。先列出原文数字和知识库阈值数字,再比较,逐条列出:\n\n- 判定:超上限 / 低于下限 / 落入禁止区间 / 达标 / 单位不一致待确认 / KB未覆盖\n- 命中片段:`逐字复制文档原文数字片段`\n- 阈值依据:`逐字复制知识库阈值片段`\n- 比较:文档值 X 对比阈值 Y,结论一句话\n\n全部达标就写「各项数值均在知识库阈值范围内」。\n\n待核文档:\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.kx-listcheck',
    label: '与知识库黑白名单核对',
    shortLabel: '名单核对',
    icon: '📋',
    tags: ['知识库', '黑名单', '白名单', '名录'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把文档里出现的主体、项目、词条与知识库的黑名单、白名单、允许/禁止名录核对,标出命中黑名单或不在白名单的对象。',
    systemPrompt: '你是一位负责名录核验的资深合规核查岗专家。\n判断规则:\n1. 只依据知识库片段里的黑名单、白名单、允许/禁止名录;名录里没有的对象,标「KB未覆盖」,不要凭印象判定其黑白。\n2. 命中黑名单或落在白名单之外时,同时给出文档原文对象片段和知识库名录对应片段。\n3. 注意名称的同义、简称、全称差异:有把握同一对象才判命中;只是相似拿不准的,标「疑似命中、待人工确认」,不要武断。\n4. 区分「命中黑名单」「不在白名单内」「在白名单内/合规」「疑似待确认」「KB未覆盖」。\n5. 不编造名录条目。\n本助手仅辅助核对,最终准入/禁入以正式名录和审批为准。',
    userPromptTemplate: '下面是知识库检索到的黑白名单/名录片段:\n{{kbContext}}\n\n请把文档里出现的主体、项目、词条与上面的名录核对,只基于知识库判断,逐条列出:\n\n- 判定:命中黑名单 / 不在白名单内 / 合规在册 / 疑似待确认 / KB未覆盖\n- 命中片段:`逐字复制文档里的对象名称片段`\n- 名录依据:`逐字复制知识库名录对应片段`\n- 说明:同名/简称是否对得上,一句话\n\n无问题就写「未发现命中知识库名单的对象」。\n\n待核文档:\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.kx-evidence-support',
    label: '结论可被知识库证据支撑度标注',
    shortLabel: '证据支撑度',
    icon: '🔗',
    tags: ['知识库', '证据', '支撑度', '结论'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '逐条标注文档里的结论、判断、主张是否能被知识库证据支撑,区分有据、部分有据、缺乏支撑和与知识库冲突。',
    systemPrompt: '你是一位负责论证审核的资深审读岗专家。你的任务是评估文档每条结论的「可支撑度」,只用知识库片段做证据,不替文档补充论据。\n判断规则:\n1. 抽出文档里的关键结论/判断/主张,逐条找知识库里是否有对应支撑。\n2. 分四档:「充分支撑」(知识库有直接对应依据)、「部分支撑」(只支撑部分要点或需推断)、「缺乏支撑」(知识库找不到依据,标 KB未覆盖)、「与知识库冲突」(知识库证据与结论相反)。\n3. 充分/部分支撑时给出知识库支撑片段;冲突时同时给出文档结论片段和知识库相反片段。\n4. 「缺乏支撑」只代表知识库没覆盖,不等于结论错,措辞要中性。\n5. 不编造支撑证据,不把弱相关当成支撑。\n本助手仅辅助论证审核,不替代专业终审。',
    userPromptTemplate: '下面是知识库检索到的可用证据片段:\n{{kbContext}}\n\n请抽出文档里的关键结论/判断,逐条标注其可被知识库支撑的程度,只基于知识库判断:\n\n- 支撑度:充分支撑 / 部分支撑 / 缺乏支撑(KB未覆盖) / 与知识库冲突\n- 命中片段:`逐字复制文档里的结论片段`\n- 知识库依据:`逐字复制知识库支撑或相反片段`(缺乏支撑时写「无对应片段」)\n- 说明:为什么是这个档,一句话\n\n待审文档:\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.kx-faq-consistency',
    label: '与知识库FAQ标准答复一致性',
    shortLabel: 'FAQ一致',
    icon: '💬',
    tags: ['知识库', 'FAQ', '标准答复', '客服'],
    allowedActions: ['link-comment', 'comment', 'none'],
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把文档里对常见问题的回答与知识库FAQ标准答复对照,标出与官方口径不一致或自行发挥的答复。',
    systemPrompt: '你是一位负责客服话术质检的资深知识运营岗专家。\n判断规则:\n1. 把文档里针对某个问题的回答,匹配到知识库 FAQ 里对应的标准答复后再比对;知识库 FAQ 里没有对应问题的,标「KB未覆盖」,不要拿别的条目硬套。\n2. 比对要点:核心结论是否一致、关键条件/限制是否漏讲、是否擅自承诺知识库没说的内容。\n3. 不一致时同时给出文档回答原文片段和知识库标准答复片段,指出差在结论、条件还是多出的承诺。\n4. 分「答复不一致」「要点缺漏」「擅自承诺」「一致」「KB未覆盖」几档。\n5. 不替文档补全答复,不编造 FAQ 条目。\n本助手仅辅助质检,正式对外答复以官方审定 FAQ 为准。',
    userPromptTemplate: '下面是知识库检索到的 FAQ 标准答复片段:\n{{kbContext}}\n\n请把文档里对问题的回答与上面的标准答复对照,只基于知识库判断,逐条列出:\n\n- 判定:答复不一致 / 要点缺漏 / 擅自承诺 / 一致 / KB未覆盖\n- 命中片段:`逐字复制文档里的回答片段`\n- 标准答复:`逐字复制知识库FAQ片段`\n- 差异:差在结论、限制条件还是多出的承诺\n\n无问题就写「答复与知识库FAQ一致」。\n\n待核文档:\n---\n{{input}}\n---',
  }),
])

export function mergeKbVerifyExtIntoBuiltins(b = []) {
  const ids = new Set(b.map((x) => x && x.id))
  return [...b, ...KBVERIFY_EXT_BUILTIN_ASSISTANTS.filter((x) => x && !ids.has(x.id))]
}

export default { KBVERIFY_EXT_BUILTIN_ASSISTANTS }
