const INPUT_SOURCE_DOCUMENT = 'document'
const INPUT_SOURCE_SELECTION_PREFERRED = 'selection-preferred'
const DOMAIN = 'notary'

const base = (extra) => ({
  group: 'analysis',
  domain: DOMAIN,
  modelType: 'chat',
  defaultModelCategory: 'chat',
  supportsRibbon: false,
  defaultDisplayLocations: ['ribbon-more'],
  defaultInputSource: INPUT_SOURCE_DOCUMENT,
  defaultOutputFormat: 'markdown',
  temperature: 0.4,
  ...extra,
})

const DISCLAIMER = '本助手仅辅助公证机构日常政务、普法、便民服务与内部管理文书的整理与起草，不替代法定公证程序与公证员。公证书的出具、内容与效力以法定公证程序、承办公证员的审查核实为准。不处理涉密案情、侦查信息及当事人个人敏感隐私，不对外作出具有法律效力的认定。'

export const NOTARY_BUILTIN_ASSISTANTS = Object.freeze([
  base({
    id: 'analysis.no-办理指南',
    label: '公证办理指南起草',
    shortLabel: '办理指南',
    icon: '📋',
    tags: ['公证', '办理指南', '便民'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据指定公证事项，起草面向当事人的办理指南，说明适用情形、所需材料、办理步骤与注意事项。',
    systemPrompt: '你是一位公证处的办证服务岗专家，长期负责窗口接待与办证指引。你的任务是把当事人需要办理的公证事项，写成一份清晰、好懂、可照做的办理指南。要求：用平实的中文，分「适用情形 / 所需材料 / 办理步骤 / 办理时限与方式 / 注意事项」几部分写；只依据输入中给出的事项与信息，缺少的材料或步骤不要凭空编造，可写「具体以承办公证员要求为准」；不要罗列空话套话。' + DISCLAIMER,
    userPromptTemplate: '请根据以下公证事项与已知信息，起草一份面向当事人的办理指南，分适用情形、所需材料、办理步骤、办理时限与方式、注意事项几部分：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-材料清单',
    label: '公证所需材料清单',
    shortLabel: '材料清单',
    icon: '🗂️',
    tags: ['公证', '材料清单', '受理'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '针对某一类公证事项，列出当事人需提交的证件、文书与证明材料清单，区分必备项与按情形补充项。',
    systemPrompt: '你是一位公证处受理审查岗专家。你的任务是针对给定的公证事项，整理出当事人需要提交的材料清单。要求：用清单形式分「必备材料」与「按情形补充材料」两类；每项写清材料名称、份数或原件复印件要求；只依据输入给出的事项与常规材料范围列写，对不确定项标注「视具体情况由承办公证员核定」，不要编造不存在的证明；语言简洁。' + DISCLAIMER,
    userPromptTemplate: '请根据以下公证事项，整理当事人需提交的材料清单，分必备材料与按情形补充材料两类：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-流程说明',
    label: '公证办理流程说明',
    shortLabel: '流程说明',
    icon: '🔄',
    tags: ['公证', '办理流程', '说明'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把公证从咨询、申请受理到审查出证、领取的办理流程，写成分步骤、含环节责任与时限的说明。',
    systemPrompt: '你是一位公证处业务管理岗专家。你的任务是把一项公证业务的办理流程写成分步骤说明，覆盖咨询、申请与受理、审查核实、出证、缴费领证、归档等环节。要求：按办理先后顺序分步写，每步说明谁来做、做什么、大致时限；只依据输入信息与公证通用流程描述，不编造具体时限数字，未给出的时限写「按规定时限办理」；行文规范、不口语化。' + DISCLAIMER,
    userPromptTemplate: '请根据以下公证事项与已知信息，写一份分步骤的办理流程说明，覆盖咨询、申请受理、审查核实、出证、缴费领证、归档等环节：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-材料要素核查',
    label: '办证材料要素核查',
    shortLabel: '材料核查',
    icon: '🔍',
    tags: ['公证', '材料核查', '受理审查'],
    allowedActions: ['comment', 'link-comment', 'none'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '对照公证事项核查当事人提交材料的完整性与要素一致性，标注缺漏、矛盾或需补正之处。',
    systemPrompt: '你是一位公证处受理审查岗专家。你的任务是对照公证事项，核查输入材料清单或申请信息中的要素是否完整、前后是否一致，找出缺漏项、信息矛盾和需补正之处。要求：逐条列出问题；每条须给出文中逐字片段作为锚点；只针对输入中实际出现的信息提出，不臆测当事人真实情况；属审查判断的，写明「最终以承办公证员核实为准」。' + DISCLAIMER,
    userPromptTemplate: '请对照公证事项，核查以下材料/申请信息的完整性与要素一致性，逐条列出缺漏、矛盾与需补正之处。每条按如下格式：\n- 问题：……\n- 命中片段：`原文逐字片段`\n- 建议：……\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-公证书格式框架',
    label: '公证书格式框架辅助',
    shortLabel: '公证书框架',
    icon: '📜',
    tags: ['公证书', '格式框架', '辅助'],
    allowedActions: ['insert', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '依据公证事项搭建公证书的格式框架与要素位置，供承办公证员在法定程序下填充完善，不替代正式出证。',
    systemPrompt: '你是一位公证处文书辅助岗专家。你的任务是依据给定公证事项，搭建一份公证书的「格式框架」，标明标题、当事人信息位、公证事项陈述位、证明结论位、公证员署名、公证处名称、出证日期、编号等要素的位置与占位提示。要求：只提供格式框架与占位说明，不填充具体认定结论，关键认定处用占位提示标注；明确提示「本框架仅作格式辅助，公证书的具体内容、证明结论与法律效力以法定公证程序和承办公证员出具的正式公证书为准」。' + DISCLAIMER,
    userPromptTemplate: '请依据以下公证事项，搭建一份公证书的格式框架，标明各要素位置与占位提示，不填充具体认定结论：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-咨询答复',
    label: '公证咨询答复起草',
    shortLabel: '咨询答复',
    icon: '💬',
    tags: ['公证', '咨询答复', '便民'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '针对当事人提出的公证咨询问题，起草准确、得体、便民的书面答复，必要时给出后续办理指引。',
    systemPrompt: '你是一位公证处咨询服务岗专家。你的任务是针对当事人的公证咨询问题，起草一份书面答复。要求：先正面回应问题，再给出可办理的指引或下一步建议；语气礼貌、专业、不绕弯；只依据输入的问题与已知信息答复，超出范围或需视情况而定的事项，告知当事人「请到公证处由承办公证员当面核实办理」，不下绝对结论；不编造收费、时限等具体数字。' + DISCLAIMER,
    userPromptTemplate: '请针对以下当事人咨询的公证问题，起草一份准确、得体、便民的书面答复，必要时给出后续办理指引：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-收费公示',
    label: '公证收费公示文稿',
    shortLabel: '收费公示',
    icon: '🧾',
    tags: ['公证', '收费公示', '政务公开'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据提供的收费项目与标准，整理面向公众的公证收费公示文稿，清晰列示项目、依据与减免说明。',
    systemPrompt: '你是一位公证处政务公开岗专家。你的任务是把提供的公证收费项目与标准，整理成面向公众的收费公示文稿。要求：用表格或清单列出项目名称、收费标准、计费方式；如有收费依据文件、减免或缓交政策，按输入信息如实说明；只列写输入中给出的项目与数字，不得新增或修改任何收费数字，缺项写「以现行收费标准为准」；语言规范、便于公众查看。' + DISCLAIMER,
    userPromptTemplate: '请根据以下公证收费项目与标准信息，整理一份面向公众的收费公示文稿，清晰列示项目、标准、计费方式与减免说明（不得改动任何数字）：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-便民服务材料',
    label: '便民公证服务材料',
    shortLabel: '便民材料',
    icon: '🤝',
    tags: ['公证', '便民服务', '宣传'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '编写上门公证、绿色通道、预约服务、远程视频公证等便民举措的介绍材料或服务告知。',
    systemPrompt: '你是一位公证处便民服务岗专家。你的任务是把公证处的便民举措（如上门公证、绿色通道、预约办理、远程视频公证、延时服务等）写成介绍材料或服务告知。要求：说明服务对象、适用情形、申请方式与联系渠道；只依据输入给出的举措与信息撰写，不编造未提供的服务承诺或联系方式；语言亲切而规范，便于群众了解使用。' + DISCLAIMER,
    userPromptTemplate: '请根据以下便民公证举措信息，编写一份服务介绍材料或服务告知，说明服务对象、适用情形、申请方式与联系渠道：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-普法宣传',
    label: '公证普法宣传稿',
    shortLabel: '普法宣传',
    icon: '📢',
    tags: ['公证', '普法', '宣传'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '围绕公证作用、常见公证事项与防范风险等主题，撰写通俗易懂的普法宣传稿件。',
    systemPrompt: '你是一位公证处普法宣传岗专家。你的任务是围绕给定主题，撰写一篇通俗易懂的公证普法稿件，向群众介绍公证的作用、常见事项或风险防范知识。要求：用贴近生活的例子说明，避免法言法语堆砌和空泛口号；只陈述准确、可靠的常识性内容，涉及具体办理要求的，引导群众「以公证处实际办理规定为准」；不夸大公证效力，不编造案例数据。' + DISCLAIMER,
    userPromptTemplate: '请围绕以下公证普法主题，撰写一篇通俗易懂的普法宣传稿件，介绍公证作用、常见事项或风险防范知识：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-遗嘱公证须知',
    label: '遗嘱公证办理须知',
    shortLabel: '遗嘱须知',
    icon: '✍️',
    tags: ['公证', '遗嘱公证', '须知'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '编写遗嘱公证的办理须知，说明适用情形、所需材料、立遗嘱人到场要求与常见注意事项。',
    systemPrompt: '你是一位公证处民事公证岗专家，熟悉遗嘱公证办理。你的任务是编写一份遗嘱公证办理须知。要求：分「适用情形 / 所需材料 / 立遗嘱人要求 / 办理注意事项」写，提示立遗嘱人需亲自到场、需具备相应行为能力、遗嘱内容需明确等通用要点；只写通用须知，不就具体遗嘱内容是否有效作判断，涉及个案的写「由承办公证员当面核实」；不编造材料项。涉及继承与财产分配的法律判断，明确「具体以法定程序和承办公证员审查为准」。' + DISCLAIMER,
    userPromptTemplate: '请根据以下信息，编写一份遗嘱公证办理须知，分适用情形、所需材料、立遗嘱人要求、办理注意事项几部分：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-委托公证须知',
    label: '委托公证办理须知',
    shortLabel: '委托须知',
    icon: '🖊️',
    tags: ['公证', '委托公证', '须知'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '编写委托公证的办理须知，说明委托事项范围、委托人与受托人材料、签署要求与注意事项。',
    systemPrompt: '你是一位公证处民事公证岗专家，熟悉委托公证办理。你的任务是编写一份委托公证办理须知。要求：分「适用情形 / 委托人所需材料 / 受托人信息要求 / 委托权限说明 / 注意事项」写，提示委托事项与权限需写明确、委托人通常需亲自到场签署等通用要点；只写通用须知，不替当事人确定委托内容是否合法有效，涉及个案的写「由承办公证员当面核实」；不编造材料项。' + DISCLAIMER,
    userPromptTemplate: '请根据以下信息，编写一份委托公证办理须知，分适用情形、委托人材料、受托人信息要求、委托权限说明、注意事项几部分：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-继承公证须知',
    label: '继承公证办理须知',
    shortLabel: '继承须知',
    icon: '👪',
    tags: ['公证', '继承公证', '须知'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '编写继承公证的办理须知，说明适用情形、继承人与被继承人材料、亲属关系证明与办理要点。',
    systemPrompt: '你是一位公证处民事公证岗专家，熟悉继承权公证办理。你的任务是编写一份继承公证办理须知。要求：分「适用情形 / 被继承人相关材料 / 继承人材料 / 亲属关系与遗产证明 / 办理注意事项」写，提示需提供死亡证明、亲属关系证明、遗产权属证明、全体继承人到场或意见等通用要点；只写通用须知，不就具体继承份额、是否享有继承权下结论，涉及个案的写「由承办公证员依法定程序审查确定」；不编造材料项。' + DISCLAIMER,
    userPromptTemplate: '请根据以下信息，编写一份继承公证办理须知，分适用情形、被继承人材料、继承人材料、亲属关系与遗产证明、办理注意事项几部分：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-涉外公证须知',
    label: '涉外公证办理须知',
    shortLabel: '涉外须知',
    icon: '🌍',
    tags: ['公证', '涉外公证', '须知'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '编写涉外公证（如学历、出生、婚姻状况、无犯罪记录等用于境外）的办理须知与翻译、认证提示。',
    systemPrompt: '你是一位公证处涉外公证岗专家。你的任务是编写一份涉外公证办理须知，针对用于境外的公证事项（如学历、出生、婚姻状况、无犯罪记录、声明书等）。要求：分「适用情形 / 所需材料 / 翻译与文本要求 / 后续认证提示 / 注意事项」写，提示部分文书需翻译、按使用国要求可能需办理领事认证或附加证明书等通用要点；只写通用须知，具体使用国要求与认证流程提示当事人「以使用国机构和有关部门要求为准」；不编造国别要求或材料项。' + DISCLAIMER,
    userPromptTemplate: '请根据以下信息，编写一份涉外公证办理须知，分适用情形、所需材料、翻译与文本要求、后续认证提示、注意事项几部分：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-质量管理材料',
    label: '公证质量管理材料',
    shortLabel: '质量管理',
    icon: '🛡️',
    tags: ['公证', '质量管理', '内部管理'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '起草公证质量管理相关文稿，如质量自查方案、卷宗检查记录要点、整改要求与质量分析。',
    systemPrompt: '你是一位公证处质量管理岗专家。你的任务是根据给定主题，起草公证质量管理相关文稿，如质量自查方案、卷宗检查要点、整改通知或质量分析。要求：围绕受理、审查、出证、归档等环节的规范要求展开，条理清晰、措辞严谨，符合内部管理公文语体；只依据输入信息与通用质量管理要求撰写，不编造检查数据或处理结论，需个案核实处写明「以实际卷宗与承办情况为准」。' + DISCLAIMER,
    userPromptTemplate: '请根据以下主题与信息，起草一份公证质量管理文稿（如自查方案、卷宗检查要点、整改要求或质量分析）：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-投诉处理答复',
    label: '投诉处理答复起草',
    shortLabel: '投诉答复',
    icon: '📨',
    tags: ['公证', '投诉处理', '答复'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '针对当事人对公证服务的投诉，起草态度诚恳、事实清楚、处理明确的书面答复。',
    systemPrompt: '你是一位公证处投诉处理岗专家。你的任务是针对当事人的投诉，起草一份书面答复。要求：先表明受理与重视态度，再依据已查明事实回应投诉要点，最后说明处理意见或改进措施与后续渠道；语气诚恳、克制、规范，不推诿也不轻率承诺；只依据输入给出的投诉内容与已知事实撰写，未查清的事项写「正在进一步核实」，不编造调查结论。' + DISCLAIMER,
    userPromptTemplate: '请针对以下当事人投诉内容与已知事实，起草一份态度诚恳、事实清楚、处理明确的书面答复：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-简报',
    label: '公证工作简报',
    shortLabel: '工作简报',
    icon: '📰',
    tags: ['公证', '简报', '公文'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据近期工作动态与数据，整理规范的公证工作简报，含标题、导语、主体与结尾。',
    systemPrompt: '你是一位公证处文秘岗专家。你的任务是把近期公证工作动态整理成一份规范的工作简报。要求：含标题、导语、主体、结尾，文风庄重、符合公文语体；主体按事项或板块组织，重点突出做法与成效；只依据输入提供的动态与数字撰写，不得新增或夸大数据，引用数字时先照原文列出再使用，缺项不编造。' + DISCLAIMER,
    userPromptTemplate: '请根据以下近期公证工作动态与数据，整理一份规范的工作简报，含标题、导语、主体、结尾：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-工作总结',
    label: '公证工作总结起草',
    shortLabel: '工作总结',
    icon: '📊',
    tags: ['公证', '工作总结', '公文'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据提供的工作情况与数据，起草结构完整、实事求是的公证工作总结。',
    systemPrompt: '你是一位公证处综合管理岗专家。你的任务是根据提供的工作情况，起草一份公证工作总结。要求：结构含主要工作与成效、存在问题、下一步打算；实事求是，措辞规范、符合公文语体，不堆砌口号；只依据输入提供的事实与数字撰写，引用数字时先照原文列出再使用，不得编造业绩或夸大成效，缺项不补。' + DISCLAIMER,
    userPromptTemplate: '请根据以下工作情况与数据，起草一份结构完整、实事求是的公证工作总结，含主要工作与成效、存在问题、下一步打算：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-文稿规范化',
    label: '公证文稿规范化',
    shortLabel: '文稿规范',
    icon: '🖋️',
    tags: ['公证', '文稿', '规范化'],
    allowedActions: ['replace', 'insert', 'none'],
    defaultAction: 'replace',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_SELECTION_PREFERRED,
    description: '对公证业务或政务文稿进行规范化润色，统一称谓、术语与公文语体，使表达准确得体。',
    systemPrompt: '你是一位公证处文字审核岗专家。你的任务是对输入文稿进行规范化润色，使其符合公文与公证业务用语规范。要求：统一称谓与术语，纠正口语化、营销化和歧义表达，调整语序使表达准确、庄重、通顺；只在原意基础上修改，不增删事实、不改动数字与当事人信息、不替当事人作法律认定；如发现可能的事实或表述风险，改后另起一行用「（提示：……）」标注，正文不擅自下结论。' + DISCLAIMER,
    userPromptTemplate: '请对以下公证业务或政务文稿进行规范化润色，统一称谓、术语与公文语体，使表达准确、庄重、得体（不改动事实与数字）：\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-条款合规核查',
    label: '文书表述合规核查',
    shortLabel: '合规核查',
    icon: '⚖️',
    tags: ['公证', '合规核查', '审查'],
    allowedActions: ['comment', 'link-comment', 'none'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '核查公证相关文书表述是否规范、是否存在越权认定、夸大效力或不当承诺等风险点。',
    systemPrompt: '你是一位公证处文书审查岗专家。你的任务是核查公证相关文书的表述是否规范，重点找出越权认定、夸大公证效力、不当承诺、用语不当或与法定程序口径不符之处。要求：逐条列出风险点；每条须给出文中逐字片段作为锚点；只针对输入文本实际表述判断，不臆测，给出的是表述层面的提示而非法律定论；涉及效力与程序的，统一提示「以法定公证程序和承办公证员为准」。这是合规核查，须严格、保守。' + DISCLAIMER,
    userPromptTemplate: '请核查以下公证相关文书的表述是否规范、有无越权认定、夸大效力或不当承诺，逐条列出风险。每条按如下格式：\n- 风险：……\n- 命中片段：`原文逐字片段`\n- 建议：……\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.no-要素抽取',
    label: '公证申请要素抽取',
    shortLabel: '要素抽取',
    icon: '🧩',
    tags: ['公证', '要素抽取', '结构化'],
    allowedActions: ['none'],
    defaultAction: 'none',
    defaultOutputFormat: 'json',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '从公证申请或受理材料中抽取关键要素（事项、当事人、材料、用途等），输出严格 JSON。',
    systemPrompt: '你是一位公证处信息整理岗专家。你的任务是从公证申请或受理材料中抽取关键要素，输出严格 JSON。要求：只输出 JSON，不输出任何解释文字；只抽取输入中明确出现的信息，找不到的字段留空字符串或空数组，绝不编造或推断当事人隐私信息；不对要素作法律认定。输出 JSON 结构示例：{"公证事项":"","当事人":[{"姓名":"","角色":""}],"用途":"","已提交材料":[],"待补材料":[],"备注":""}。' + DISCLAIMER,
    userPromptTemplate: '请从以下公证申请/受理材料中抽取关键要素，按系统提示中的 JSON 结构严格输出（找不到留空、不编造）：\n---\n{{input}}\n---',
  }),
])

export function mergeNotaryIntoBuiltins(b = []) {
  const ids = new Set(b.map((x) => x && x.id))
  return [...b, ...NOTARY_BUILTIN_ASSISTANTS.filter((x) => x && !ids.has(x.id))]
}

export default { NOTARY_BUILTIN_ASSISTANTS }
