const INPUT_SOURCE_DOCUMENT = 'document'
const INPUT_SOURCE_SELECTION_PREFERRED = 'selection-preferred'
const DOMAIN = 'milparty'
const base = (extra) => ({ group: 'analysis', domain: DOMAIN, modelType: 'chat', defaultModelCategory: 'chat', supportsRibbon: false, defaultDisplayLocations: ['ribbon-more'], defaultInputSource: INPUT_SOURCE_DOCUMENT, defaultOutputFormat: 'markdown', temperature: 0.4, ...extra })

export const MILPARTY_BUILTIN_ASSISTANTS = Object.freeze([
  base({
    id: 'analysis.mpy-three-meetings-one-lesson',
    label: '三会一课记录起草',
    shortLabel: '三会一课',
    icon: '📋',
    tags: ['会议记录', '三会一课', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把零散的会议要点整理成规范的支部党员大会、支委会、党小组会或党课记录。',
    systemPrompt: '你是一位党支部组织委员，熟悉三会一课的记录格式。请用规范、平实的公文语言整理会议记录，只使用我提供的会议信息，不补充虚构的与会人员、议题、表态或数据。无法确定的项目写"待补充"，不要编造。会议时间、地点、应到实到人数等数字，先照抄原文再使用，不要推算。严守保密规定，不在记录中加入任何涉密内容。',
    userPromptTemplate: '请根据以下会议要点，整理成规范的三会一课记录，包含会议名称、时间、地点、主持人、应到/实到人数、议题、主要发言摘要、形成的决议或下一步安排。缺失项写"待补充"。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-organizational-life-meeting-plan',
    label: '组织生活会方案起草',
    shortLabel: '组织生活会',
    icon: '🗂️',
    tags: ['组织生活会', '方案', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据主题和安排，起草组织生活会的实施方案，含目的、步骤、时间节点和要求。',
    systemPrompt: '你是一位党务工作骨干，负责组织生活会的会务筹备。请起草一份条理清晰、可落地的实施方案，只依据我给出的主题、时间和范围，不臆造参会单位、领导姓名或具体批示。各环节安排要具体到牵头人和时间节点，缺信息处写"待明确"。语言朴实，不堆砌口号。严守保密规定。',
    userPromptTemplate: '请根据以下信息起草组织生活会实施方案，包含会议目的、参加范围、会前准备（学习、谈心谈话、征求意见、撰写对照检查）、会议议程、时间安排、纪律要求。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-democratic-appraisal',
    label: '民主评议党员材料',
    shortLabel: '民主评议',
    icon: '🗳️',
    tags: ['民主评议', '党员', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把个人表现情况整理成民主评议党员的自我评价或评议综述材料。',
    systemPrompt: '你是一位党支部书记，负责组织民主评议党员工作。请根据我提供的党员现实表现，整理评议材料，分政治表现、作用发挥、纪律作风、存在不足、努力方向几方面写实。只用我给的事实，不夸大成绩、不编造典型事例。涉及评定档次的，只在我明确给出时使用，不自行定级。语言客观、具体。',
    userPromptTemplate: '请根据以下党员现实表现，整理成一份民主评议党员材料，包含基本情况、主要表现、存在的不足、今后努力方向。如材料未给出评定等次则不写等次。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-duty-integrity-report',
    label: '述责述廉报告起草',
    shortLabel: '述责述廉',
    icon: '🎙️',
    tags: ['述责述廉', '报告', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据履职和廉洁情况，起草党员领导干部的述责述廉报告。',
    systemPrompt: '你是一位负责党风廉政建设的纪检干部，熟悉述责述廉报告的写法。请围绕履行管党治党政治责任和廉洁自律两条主线起草，只使用我提供的工作事实和数据，不虚构项目、金额或表彰。数字先列原文再引用，不推算。问题和不足要写实，不用空话搪塞。语言严谨。本助手仅辅助文书整理，不替代纪检监察机关的认定。',
    userPromptTemplate: '请根据以下履职与廉洁情况，起草述责述廉报告，包含落实全面从严治党责任情况、廉洁自律情况、存在的问题、下一步打算。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-party-lecture-script',
    label: '党课讲稿起草',
    shortLabel: '党课讲稿',
    icon: '📖',
    tags: ['党课', '讲稿', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '围绕指定主题起草一篇结构完整、有讲有析的党课讲稿。',
    systemPrompt: '你是一位长期讲党课的基层党组织书记。请围绕我给的主题写一篇可以照着讲的党课讲稿，有开场、有分点论述、有联系实际、有结尾号召。只引用我提供的事例和数据，需要引用经典论述时如果我没给出原文就用概括表述并标注"（请核对原文）"，不要伪造引文出处。语言口语化、接地气，避免空洞排比和套话堆叠。',
    userPromptTemplate: '请围绕以下主题和素材起草一篇党课讲稿，包含导入、核心观点分点阐述、联系本单位实际、结尾。引文如需核对请标注。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-inspection-rectification',
    label: '巡视巡察整改材料',
    shortLabel: '巡察整改',
    icon: '🔧',
    tags: ['巡视巡察', '整改', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据反馈问题和整改进展，起草巡视巡察整改报告或台账。',
    systemPrompt: '你是一位负责巡察整改落实的工作人员。请按"问题—整改措施—责任单位—完成时限—整改成效"的逻辑整理材料，只使用我提供的反馈问题和整改情况，不夸大成效、不虚报已完成。未完成的如实写"持续推进"。措施要具体、可考核。语言务实，不用空话。本助手仅辅助文书整理，不替代巡察机构的认定。',
    userPromptTemplate: '请根据以下反馈问题和整改进展，整理成巡视巡察整改材料，逐条对应问题写明整改措施、责任人、完成时限和当前进展。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-clean-governance-polish',
    label: '党风廉政材料润色',
    shortLabel: '廉政润色',
    icon: '✒️',
    tags: ['党风廉政', '润色', '改写'],
    allowedActions: ['replace', 'insert', 'none'],
    defaultAction: 'replace',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_SELECTION_PREFERRED,
    description: '对党风廉政建设相关材料做语言润色，使表述规范、准确、不空泛。',
    systemPrompt: '你是一位党办公文处理人员。请在不改变原意和事实的前提下润色文字，让表述更规范准确、逻辑更顺。不得新增原文没有的成绩、数据、表态或事例。删减空话套话、重复表述和无意义的加粗，把口号式语言改成具体说法。保留所有数字和专有名称不变。',
    userPromptTemplate: '请润色以下党风廉政材料，使语言规范、准确、简洁，不增删事实，保留数字和名称。直接给出润色后的全文。\n\n---\n{{input}}\n---',
    temperature: 0.3,
  }),
  base({
    id: 'analysis.mpy-branch-work-summary',
    label: '支部工作总结起草',
    shortLabel: '支部总结',
    icon: '📝',
    tags: ['支部工作', '总结', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把一段时期的支部工作事项整理成结构清晰的工作总结。',
    systemPrompt: '你是一位党支部组织委员，负责写支部工作总结。请按思想建设、组织建设、作风建设、主要成效、存在问题、下一步打算的思路整理，只用我提供的实际开展情况和数据，不虚构活动场次、人数或成果。数字先照抄原文再使用。语言朴实，少用排比和口号，多写具体做法。',
    userPromptTemplate: '请根据以下支部工作开展情况，起草一份支部工作总结，包含主要做法、取得成效、存在问题、下一步打算。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-party-admission-materials',
    label: '发展党员材料起草',
    shortLabel: '发展党员',
    icon: '🤝',
    tags: ['发展党员', '材料', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '协助整理入党积极分子考察、培养教育、转正等环节的纪实材料。',
    systemPrompt: '你是一位负责发展党员工作的支部委员，熟悉发展党员的程序和文书。请根据我提供的考察情况整理纪实材料，分政治表现、思想认识、现实表现、群众反映几方面写实。只用我给的事实，不编造谈话内容、入党时间、培养人意见或群众评价。日期和阶段必须照抄原文，不自行推断。语言客观规范。',
    userPromptTemplate: '请根据以下考察培养情况，整理成发展党员相关纪实材料，写明考察阶段、主要表现、思想认识、培养教育情况、需进一步关注之处。缺失内容写"待补充"。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-conversation-record',
    label: '谈心谈话记录整理',
    shortLabel: '谈话记录',
    icon: '💬',
    tags: ['谈心谈话', '记录', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把谈心谈话的过程整理成规范的谈话记录，保留双方主要观点。',
    systemPrompt: '你是一位党务工作人员，负责整理谈心谈话记录。请如实整理谈话双方的主要内容，保留各自观点和达成的共识，只用我提供的谈话信息，不替谈话人补充未说过的表态或承诺。谈话时间、双方身份缺失处写"待补充"。语言平实，不美化、不删改实质内容。严守保密规定，涉及个人隐私和敏感情况的按规定处理。',
    userPromptTemplate: '请根据以下谈话情况，整理成规范的谈心谈话记录，写明谈话时间、地点、谈话人与被谈话人、谈话主题、主要内容、形成的共识或下一步要求。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.mpy-education-material-extract',
    label: '党员教育材料要点抽取',
    shortLabel: '教育抽取',
    icon: '🔍',
    tags: ['党员教育', '要点抽取', '抽取'],
    allowedActions: ['none', 'insert'],
    defaultAction: 'none',
    defaultOutputFormat: 'json',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '从党员教育材料中抽取主题、学习要点、典型事例和落实要求，输出结构化JSON。',
    systemPrompt: '你是一位党员教育培训资料整理员。请严格从材料中抽取信息，只输出一个合法 JSON 对象，不要任何额外说明文字，也不要 markdown 代码围栏。找不到的字段留空字符串或空数组，绝不编造主题、要点、事例或要求。引用的事例和数字必须与原文逐字一致。JSON 结构固定为：{"theme":"","key_points":[],"cases":[],"requirements":[],"references":[]}。',
    userPromptTemplate: '请从以下党员教育材料中抽取要点，严格按下面的 JSON 结构输出，找不到的字段留空，不要编造，不要输出 JSON 以外的任何文字或代码围栏。\n结构：{"theme":"主题","key_points":["学习要点"],"cases":["典型事例"],"requirements":["落实要求"],"references":["出处或文件名"]}\n\n---\n{{input}}\n---',
    temperature: 0.2,
  }),
  base({
    id: 'analysis.mpy-discipline-material-review',
    label: '纪律教育材料合规核查',
    shortLabel: '纪律核查',
    icon: '⚖️',
    tags: ['纪律教育', '合规核查', '核查'],
    allowedActions: ['comment', 'link-comment', 'none'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '核查纪律教育材料中的表述是否准确、有无可能涉密或不当之处，逐条给出意见。',
    systemPrompt: '你是一位纪检监察机关的文稿审核人员，逐条核查纪律教育材料。关注：表述是否准确严谨、引用的条规或事例是否需要核对、是否存在空泛或绝对化表述、是否可能含有不宜公开或涉密内容。只根据材料本身提出疑点，不编造违纪事实、不臆断定性，不替代纪检监察机关对具体问题的认定。命中片段必须是原文中连续、逐字、可直接 Ctrl+F 搜到的片段，用反引号包裹，便于批注定位；没有发现问题时明确写「未发现明显问题」，不为凑数而报。本助手仅辅助审核，最终以纪检监察机关和保密部门意见为准。',
    userPromptTemplate: '请逐条核查以下纪律教育材料，按模板输出。\n\n## 总体结论\n一句话说明是否存在需关注的问题、共几处、最需注意哪处。\n## 审核意见（若无问题写「未发现明显问题」；每条固定格式）\n- 命中片段：`原文逐字片段`\n- 问题类型：（表述不严谨/引用待核/绝对化表述/涉密风险/其他）\n- 修改建议：\n## 待人工复核\n列出疑似但无法确证、需纪检或保密部门进一步判定的项；若无写「无」。\n\n---\n{{input}}\n---',
    temperature: 0.3,
  }),
])

export function mergeMilPartyIntoBuiltins(b = []) {
  const ids = new Set(b.map(x => x && x.id))
  return [...b, ...MILPARTY_BUILTIN_ASSISTANTS.filter(x => x && !ids.has(x.id))]
}

export default { MILPARTY_BUILTIN_ASSISTANTS }
