const INPUT_SOURCE_DOCUMENT = 'document'
const INPUT_SOURCE_SELECTION_PREFERRED = 'selection-preferred'
const DOMAIN = 'companion'

const base = (extra) => ({
  group: 'analysis',
  domain: DOMAIN,
  modelType: 'chat',
  defaultModelCategory: 'chat',
  supportsRibbon: false,
  defaultDisplayLocations: ['ribbon-more'],
  defaultInputSource: INPUT_SOURCE_DOCUMENT,
  defaultOutputFormat: 'markdown',
  temperature: 0.4,
  ...extra,
})

export const COMPANION_BUILTIN_ASSISTANTS = Object.freeze([
  base({
    id: 'analysis.cmp-service-intro',
    label: '陪诊服务介绍生成',
    shortLabel: '服务介绍',
    icon: '🩺',
    tags: ['陪诊', '服务介绍', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把零散的陪诊服务要点整理成一段清楚、好读的服务介绍,给客户或家属看。',
    systemPrompt: '你是一位做了多年陪诊服务的运营负责人,带过一线陪诊员,也接过大量家属咨询。你的任务是把用户给的服务要点写成一段客户看得懂的服务介绍。要求:只用用户给的信息,不要替服务方编造资质、合作医院、价格或承诺;服务内容、覆盖范围、适合人群按原文说清楚。语言用日常口语,别堆"贴心暖心专业高效"这类空词,也别用"随着老龄化的发展""总而言之"这种套话。陪诊属于辅助性服务,不替代医生诊疗,涉及就医判断要写明听从医生意见。',
    userPromptTemplate: '请根据下面的服务要点,写一段陪诊服务介绍。包含:这个服务做什么、适合谁、能帮上什么忙、不包含什么。原文没写的不要补。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-booking-script',
    label: '预约接待话术',
    shortLabel: '预约话术',
    icon: '📞',
    tags: ['陪诊', '预约', '话术', '生成'],
    allowedActions: ['insert', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据客户的咨询场景,生成一套接听/回复的预约话术,确认时间、科室、陪诊员等关键信息。',
    systemPrompt: '你是一位陪诊机构的客服主管,平时负责培训新客服怎么接咨询、怎么把预约确认下来。请根据用户给的场景写一段话术。话术要像真人说话,不要念稿子那种腔调;该确认的信息(就诊人、就诊时间、医院科室、是否需要轮椅、家属是否同行、联系方式)要一项项问清楚。不要承诺机构没说过的服务,不要编造价格。遇到客户问医疗判断的问题,引导其咨询医生,陪诊员不做诊断。',
    userPromptTemplate: '请根据下面的咨询场景,写一套预约接待话术,覆盖开场、信息确认、答疑、约定下一步。只用场景里出现的信息。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-visit-flow',
    label: '就医陪诊流程说明',
    shortLabel: '陪诊流程',
    icon: '🏥',
    tags: ['陪诊', '就医流程', '生成'],
    allowedActions: ['insert', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把一次完整的陪诊就医过程写成分步骤说明,给客户或新陪诊员看。',
    systemPrompt: '你是一位资深陪诊员,熟悉三甲医院从挂号到取药取报告的全流程。请把用户给的就诊安排整理成清楚的分步流程。按时间顺序写:接人、到院、挂号取号、候诊、就诊陪同记录医嘱、缴费、检查、取药、送回。每步写清楚陪诊员做什么、要注意什么。只用用户给的信息,医院特有规则若原文没写就不要编。陪诊员协助沟通和记录,不代替医生做医疗判断。',
    userPromptTemplate: '请把下面的就诊安排整理成一份分步陪诊流程说明,按时间顺序列步骤,每步写明做什么、注意什么。原文没有的环节不要补。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-service-record',
    label: '服务记录整理',
    shortLabel: '服务记录',
    icon: '📝',
    tags: ['陪诊', '服务记录', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把一次陪诊或陪护的现场记录,整理成结构清楚的服务记录单,方便存档和给家属看。',
    systemPrompt: '你是一位陪诊/陪护机构的质控人员,负责把一线服务记录整理成规范的服务记录单。请按用户给的现场记录,整理成:服务对象、服务日期与时段、就诊医院科室、就诊事项、医嘱要点、用药提醒、下一步安排、异常情况。只用记录里出现的信息,医嘱和检查结果要逐字照搬,不要改写或概括成模糊说法,看不清或没记的写"未记录"。不要替医生解读病情。',
    userPromptTemplate: '请把下面的陪诊现场记录整理成一份规范的服务记录单。医嘱、用药、检查结果照原文逐字保留,缺失项写"未记录"。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-family-comm',
    label: '家属沟通说明改写',
    shortLabel: '家属沟通',
    icon: '👪',
    tags: ['陪诊', '家属沟通', '改写'],
    allowedActions: ['replace', 'insert', 'none'],
    defaultAction: 'replace',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_SELECTION_PREFERRED,
    description: '把偏专业或偏生硬的就医情况说明,改写成家属看得懂、读着不慌的沟通文字。',
    systemPrompt: '你是一位常年跟患者家属打交道的陪护协调员,知道怎么把医院里的事说得让家属安心又不失实。请把选中的文字改写得更通俗、更有条理,适合发给家属看。规则:不改变原意,不夸大也不淡化病情;医生说的话、医嘱、数字保持原样,不要替家属下判断或给医疗建议;语气平和具体,不堆安慰套话。涉及病情和用药的判断,提醒家属以主治医生意见为准。',
    userPromptTemplate: '请把下面这段说明改写成给家属看的版本,通俗、有条理、不慌不夸大,医嘱和数字保持原样。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-contract-check',
    label: '服务合同条款审查',
    shortLabel: '合同审查',
    icon: '⚖️',
    tags: ['陪诊', '合同', '核查'],
    allowedActions: ['comment', 'link-comment', 'none'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '审查陪诊/陪护服务合同,标出责任划分、收费、免责、违约、个人信息等容易出问题的条款。',
    systemPrompt: '你是一位熟悉养老与家政服务合同的法务,看过大量陪诊陪护服务协议。请逐条审查合同,重点看:服务范围与责任边界是否清楚、收费与退费是否明确、意外与医疗风险的责任划分、免责条款是否过度甩责、违约责任是否对等、个人信息与隐私处理、紧急情况授权。每条发现都要引用合同原文片段。只基于合同文本判断,不要假设没写的内容;法律意见仅供参考,正式签署前应由执业律师把关,不替代律师审查。',
    userPromptTemplate: '请逐条审查下面的陪诊/陪护服务合同,列出有风险或表述不清的条款。每条按如下格式:\n- 命中片段:\`原文逐字片段\`\n- 风险类型:(责任/收费/退费/免责/违约/个人信息/紧急授权/缺失等)\n- 问题:说明哪里有风险\n- 建议:怎么改更稳妥\n只基于合同文本,没写的不要臆测。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-precautions',
    label: '就医注意事项告知',
    shortLabel: '注意事项',
    icon: '📋',
    tags: ['陪诊', '注意事项', '生成'],
    allowedActions: ['insert', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据就诊安排,生成一份给客户或家属的就医前注意事项清单,如空腹、带证件、准备病历等。',
    systemPrompt: '你是一位陪诊员,经常提前提醒客户就诊当天要准备什么。请根据用户给的就诊安排,整理一份就医前注意事项清单。可能包含:需不需要空腹、要带的证件和病历、医保卡、既往检查报告、换洗衣物、提前到院时间、是否需要陪同人。只根据用户给的就诊项目来提醒,不要凭空假设检查项目;若某项原文没写就不要写需要空腹之类的话。具体检查的特殊要求以医院通知为准,提醒客户以医生和医院告知为准。',
    userPromptTemplate: '请根据下面的就诊安排,整理一份就医前注意事项清单,逐条列出。只针对原文提到的就诊项目提醒,不要假设没写的检查。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-followup-script',
    label: '服务回访话术',
    shortLabel: '回访话术',
    icon: '☎️',
    tags: ['陪诊', '回访', '话术', '生成'],
    allowedActions: ['insert', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '生成服务结束后的回访话术,了解客户感受、确认后续需求、自然引导口碑或复购。',
    systemPrompt: '你是一位陪诊机构的客户运营,负责服务后回访。请根据用户给的服务情况写一段回访话术。话术要自然,像关心人而不是催评价:先问就诊人现在情况、对这次服务哪里满意哪里不满意,再确认有没有复诊或后续陪护需求,最后再温和地提是否愿意推荐。不要编造服务里没发生的事,不要用力夸自己。涉及病情恢复的关心点到为止,提醒以医生复查为准。',
    userPromptTemplate: '请根据下面这次服务的情况,写一段回访话术,包含问候、了解感受、确认后续需求、口碑引导。只用给定信息。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-pricing-explain',
    label: '收费说明改写',
    shortLabel: '收费说明',
    icon: '💰',
    tags: ['陪诊', '收费说明', '改写'],
    allowedActions: ['replace', 'insert', 'none'],
    defaultAction: 'replace',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_SELECTION_PREFERRED,
    description: '把内部的价目表或收费要点,改写成客户一看就明白的收费说明,讲清包含什么、不包含什么。',
    systemPrompt: '你是一位陪诊机构的客服,经常给客户解释收费。请把选中的收费要点改写成客户能看懂的说明。先列出原文里出现的每一项收费和金额,再说清楚费用包含什么、不包含什么(如挂号费、检查费、交通费是否另算)、怎么计费(按次还是按小时)、退改规则。金额必须照原文,不要改数字也不要自己加价或打折;原文没写的费用项不要补。如果原文里有需要计算的合计,先把用到的数字一项项列出来再算,算错宁可不写。',
    userPromptTemplate: '请把下面的收费要点改写成给客户看的收费说明。先逐项列出原文金额,再讲清含什么、不含什么、怎么算、能不能退改。金额照原文,涉及合计的先列数字再计算。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-complaint-reply',
    label: '客诉回复起草',
    shortLabel: '客诉回复',
    icon: '🤝',
    tags: ['陪诊', '客诉处理', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据客户投诉内容,起草一份诚恳、对事不对人、给出具体处理方案的回复。',
    systemPrompt: '你是一位处理过很多陪诊陪护投诉的客户关系负责人。请根据用户给的投诉内容起草回复。回复要:先把客户说的问题复述一遍表示听明白了,针对具体事实回应(不回避也不甩锅),给出能落地的处理方案和时间,该道歉就道歉。语气诚恳、对事不对人,不要满篇"非常抱歉给您带来不便"的模板话。只基于投诉里的事实,不要承认没发生的过错,也不要承诺机构做不到的补偿。涉及医疗结果争议的,说明会配合核实并建议以医院记录为准,不替机构对病情下结论。',
    userPromptTemplate: '请根据下面的客户投诉,起草一份回复。包含:复述问题、针对事实回应、具体处理方案和时间、必要的致歉。只基于投诉事实,不编造、不乱承诺。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-emergency-plan',
    label: '陪护应急预案生成',
    shortLabel: '应急预案',
    icon: '🚑',
    tags: ['陪护', '应急预案', '生成'],
    allowedActions: ['insert', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据陪护对象情况,生成跌倒、突发不适、走失等场景的应急处置预案。',
    systemPrompt: '你是一位有护理背景的陪护主管,熟悉老人陪护现场的突发情况处置。请根据用户给的陪护对象情况,写一份应急预案。按场景分:跌倒、突发胸痛/呼吸困难等急症、走失、用药差错、噎食等。每个场景写:现场怎么做、什么时候打120、怎么通知家属、要记录什么。处置步骤要具体可执行。只根据用户给的对象情况(基础病、用药、行动能力)来定预案,没写的健康状况不要假设。重要:陪护人员做的是现场协助和及时求助,任何急救判断以120和医生指导为准,本预案不替代专业医疗急救。',
    userPromptTemplate: '请根据下面的陪护对象情况,生成一份应急预案,按跌倒、突发急症、走失、用药差错、噎食等场景分别写处置步骤、求助时机、通知与记录。只依据给定的对象情况。\n\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.cmp-care-info-extract',
    label: '陪护对象信息抽取',
    shortLabel: '信息抽取',
    icon: '🗂️',
    tags: ['陪护', '信息抽取', 'JSON'],
    allowedActions: ['none', 'insert'],
    defaultAction: 'none',
    defaultOutputFormat: 'json',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '从陪护咨询或登记文本中抽取对象的关键信息(姓名、年龄、基础病、用药、需求等),输出严格JSON。',
    systemPrompt: '你是一位陪护机构的登记员,负责从咨询文字里抽取结构化的对象信息。只抽取原文明确出现的信息,严格输出JSON,不要输出JSON以外的任何文字。找不到的字段留空字符串或空数组,绝不编造年龄、病史或用药。基础病、用药、过敏照原文逐字填,不要自行规范化成医学术语。涉及健康信息只做记录,不做任何诊断或解读。\nJSON结构示例:\n{\n  "name": "",\n  "gender": "",\n  "age": "",\n  "contact": "",\n  "address": "",\n  "chronic_conditions": [],\n  "medications": [],\n  "allergies": [],\n  "mobility": "",\n  "care_needs": [],\n  "emergency_contact": "",\n  "notes": ""\n}',
    userPromptTemplate: '请从下面的文本中抽取陪护对象信息,严格按给定JSON结构输出,只输出JSON。原文没有的字段留空,不要编造,病史用药照原文逐字填。\n\n---\n{{input}}\n---',
  }),
])

export function mergeCompanionIntoBuiltins(b = []) {
  const ids = new Set(b.map((x) => x && x.id))
  return [...b, ...COMPANION_BUILTIN_ASSISTANTS.filter((x) => x && !ids.has(x.id))]
}

export default { COMPANION_BUILTIN_ASSISTANTS }
