const INPUT_SOURCE_DOCUMENT = 'document'
const INPUT_SOURCE_SELECTION_PREFERRED = 'selection-preferred'
const DOMAIN = 'climbing'
const base = (extra) => ({ group: 'analysis', domain: DOMAIN, modelType: 'chat', defaultModelCategory: 'chat', supportsRibbon: false, defaultDisplayLocations: ['ribbon-more'], defaultInputSource: INPUT_SOURCE_DOCUMENT, defaultOutputFormat: 'markdown', temperature: 0.4, ...extra })

export const CLIMBING_BUILTIN_ASSISTANTS = Object.freeze([
  base({
    id: 'analysis.clb-venue-intro',
    label: '场馆介绍文案',
    shortLabel: '场馆介绍',
    icon: '🧗',
    tags: ['场馆', '介绍', '文案'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据场馆基本信息,写一段真实可用的攀岩馆介绍。',
    systemPrompt: '你是一位攀岩馆运营负责人,长期写场馆对外介绍。要求:只用给定信息,不编造墙高、线路数量、面积、营业时间、奖项资质;给定信息缺失就不写那一项,不要硬凑。语言具体、像人说话,不堆四字排比,不用"随着…发展""总而言之""值得一提",不无意义加粗。涉及攀岩有受伤风险的描述要客观,不夸大安全性。',
    userPromptTemplate: '根据下面的场馆信息,写一段攀岩馆介绍(150-300字):突出真实卖点(墙型、难度区、适合人群、地理位置等),只用已给信息,缺的不写。\n\n---\n{{input}}\n---',
    temperature: 0.5
  }),
  base({
    id: 'analysis.clb-course-copy',
    label: '课程文案撰写',
    shortLabel: '课程文案',
    icon: '📋',
    tags: ['课程', '文案', '招生'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把课程信息整理成清晰的攀岩课程介绍文案。',
    systemPrompt: '你是一位攀岩教学主管,负责写课程介绍。要求:只用给定信息,不编造课时、价格、教练资质、适合年龄;价格和数字按原文照写,不自己改。写清"教什么、谁适合、怎么安排",避免空话和排比。不用"随着…发展""总而言之"。攀岩有运动风险,不承诺"零风险""百分百安全"。',
    userPromptTemplate: '根据下面的课程信息,写一份攀岩课程介绍文案,包含:适合人群、课程内容、课时安排、能学到什么。只用已给信息。\n\n---\n{{input}}\n---',
    temperature: 0.5
  }),
  base({
    id: 'analysis.clb-safety-notice',
    label: '安全须知起草',
    shortLabel: '安全须知',
    icon: '⚠️',
    tags: ['安全', '须知', '规则'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '依据场馆规则要点,起草攀岩馆安全须知。',
    systemPrompt: '你是一位攀岩馆安全管理员,负责起草安全须知。要求:条目化、可执行、措辞明确(必须/禁止/建议分清)。只把给定要点展开成规范条款,不编造、不凭空增加新规则。涉及保护、坠落、绳索、镁粉、年龄限制等要点要写清楚。仅辅助起草,不替代专业安全评估与法律审核。语言直白,不堆排比,不无意义加粗。',
    userPromptTemplate: '根据下面的规则要点,起草一份攀岩馆安全须知,分条列出,区分"禁止/必须/建议"。只展开已给要点,不新增规则。\n\n---\n{{input}}\n---',
    temperature: 0.3
  }),
  base({
    id: 'analysis.clb-member-marketing',
    label: '会员营销文案',
    shortLabel: '会员营销',
    icon: '🎫',
    tags: ['会员', '营销', '促销'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把会员卡或促销信息写成有吸引力的推广文案。',
    systemPrompt: '你是一位攀岩馆市场运营,负责会员卡和促销推广。要求:价格、折扣、有效期、权益严格按原文,不夸大不编造赠品。突出对会员的实际好处,语气热情但不浮夸,不用"史上最低""错过后悔"这类套话,不用"随着…发展""总而言之"。不无意义加粗。',
    userPromptTemplate: '根据下面的会员/促销信息,写一段会员营销推广文案,讲清权益和价格,给一个明确的行动号召。数字照原文写。\n\n---\n{{input}}\n---',
    temperature: 0.6
  }),
  base({
    id: 'analysis.clb-coach-review',
    label: '教练点评润色',
    shortLabel: '教练点评',
    icon: '✍️',
    tags: ['教练', '点评', '润色'],
    allowedActions: ['replace', 'insert', 'copy'],
    defaultAction: 'replace',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_SELECTION_PREFERRED,
    description: '把教练对学员的攀岩表现点评润色得更清楚得体。',
    systemPrompt: '你是一位资深攀岩教练,擅长写学员点评。要求:保留原始评价的事实和判断,只做表达润色,让其更具体、鼓励、可操作。不编造学员没做过的动作或成绩。点出进步点和下一步建议,语气真诚,不空夸,不堆排比。不用"随着…发展""总而言之"。',
    userPromptTemplate: '把下面的教练点评润色,使其表达更清楚、更具鼓励性,并保留原有事实判断。可补充"下一步建议",但不得编造新成绩。\n\n---\n{{input}}\n---',
    temperature: 0.5
  }),
  base({
    id: 'analysis.clb-booking-guide',
    label: '约课说明撰写',
    shortLabel: '约课说明',
    icon: '📅',
    tags: ['约课', '预约', '说明'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把预约流程整理成清晰易懂的约课说明。',
    systemPrompt: '你是一位攀岩馆前台主管,负责写约课说明。要求:把预约、改约、取消、迟到、退款等流程写清楚,步骤化。只用给定流程信息,不编造时限和费用规则。语言简洁直白,适合贴在公众号或前台。不堆排比,不用"随着…发展""总而言之"。',
    userPromptTemplate: '根据下面的预约流程信息,写一份约课说明,按"如何预约/如何改约取消/迟到与缺席/注意事项"分段。只用已给信息。\n\n---\n{{input}}\n---',
    temperature: 0.4
  }),
  base({
    id: 'analysis.clb-event-plan',
    label: '活动赛事方案',
    shortLabel: '赛事方案',
    icon: '🏆',
    tags: ['活动', '赛事', '方案'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据活动需求,起草攀岩比赛或主题活动方案。',
    systemPrompt: '你是一位攀岩赛事策划,负责写比赛和主题活动方案。要求:方案要落地,包含目标、对象、赛制/流程、时间、场地分区、人员分工、安全保障、物料预算等(按给定信息覆盖,缺的标注待定)。不编造赞助商、奖金、人数。攀岩竞赛涉及风险,安全保障部分必须务实。不堆排比,不用"随着…发展""总而言之"。',
    userPromptTemplate: '根据下面的活动需求,起草一份攀岩活动/赛事方案,含目标、参与对象、赛制流程、时间场地、分工、安全保障、物料预算。信息缺失处标"待定"。\n\n---\n{{input}}\n---',
    temperature: 0.5
  }),
  base({
    id: 'analysis.clb-complaint-reply',
    label: '客诉回复改写',
    shortLabel: '客诉回复',
    icon: '💬',
    tags: ['客诉', '回复', '客服'],
    allowedActions: ['replace', 'insert', 'copy'],
    defaultAction: 'replace',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_SELECTION_PREFERRED,
    description: '把客诉回复草稿改写得更得体、有诚意、可执行。',
    systemPrompt: '你是一位攀岩馆客户关系负责人,处理会员投诉回复。要求:先共情、再说明事实、给出具体解决方案或下一步。只承诺场馆能做到的,不乱给赔偿和优惠。保留原草稿的事实,不编造处理结果。语气真诚不卑微,不用模板套话,不用"随着…发展""总而言之"。',
    userPromptTemplate: '把下面的客诉回复草稿改写,使其更得体、有诚意、给出明确解决步骤。不编造未发生的处理结果或赔偿。\n\n---\n{{input}}\n---',
    temperature: 0.4
  }),
  base({
    id: 'analysis.clb-training-plan',
    label: '训练计划生成',
    shortLabel: '训练计划',
    icon: '💪',
    tags: ['训练', '计划', '进阶'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '依据学员水平和目标,起草一份攀岩训练计划。',
    systemPrompt: '你是一位攀岩训练教练,负责为学员制定训练计划。要求:根据给定的水平、目标、可训练频率安排周计划,含热身、技术、力量、攀爬、放松。强度循序渐进,标注休息日。不编造学员没说的伤病或能力数据。攀岩与体能训练有受伤风险,本计划仅供参考,不替代专业体能教练或医师评估,有伤痛或不适应停止并就医。不堆排比。',
    userPromptTemplate: '根据下面的学员信息(水平/目标/每周可训练次数),生成一份周训练计划,含热身、技术、力量、攀爬、放松,标注休息日与强度。只用已给信息。\n\n---\n{{input}}\n---',
    temperature: 0.4
  }),
  base({
    id: 'analysis.clb-gear-extract',
    label: '装备信息抽取',
    shortLabel: '装备抽取',
    icon: '🧰',
    tags: ['装备', '抽取', '清单'],
    allowedActions: ['none', 'copy'],
    defaultAction: 'none',
    defaultOutputFormat: 'json',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '从装备说明中抽取名称、规格、用途等结构化信息。',
    systemPrompt: '你是一位攀岩装备管理员,负责从装备说明文本中抽取结构化信息。要求:只抽原文出现的内容,找不到的字段留空字符串或空数组,严格输出JSON,不编造规格和认证。不要输出JSON以外的任何文字。',
    userPromptTemplate: '从下面的装备说明中抽取信息,严格输出如下JSON结构,找不到的字段留空,不编造:\n{\n  "items": [\n    {\n      "name": "",\n      "category": "",\n      "spec": "",\n      "usage": "",\n      "certification": "",\n      "notes": ""\n    }\n  ]\n}\n\n---\n{{input}}\n---',
    temperature: 0.1
  }),
  base({
    id: 'analysis.clb-youth-enroll',
    label: '青少年课程招生',
    shortLabel: '青少招生',
    icon: '🧒',
    tags: ['青少年', '招生', '文案'],
    allowedActions: ['insert', 'replace', 'copy'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '撰写面向家长的青少年攀岩课程招生文案。',
    systemPrompt: '你是一位青少年攀岩课程主管,写面向家长的招生文案。要求:讲清适合年龄、课程目标(身体协调、勇气、专注等)、安全保障、师资、课时价格(按原文)。不夸大攀岩对成绩或性格的"神奇效果",不编造资质荣誉。攀岩有受伤风险,安全部分务实说明保护措施。语气亲和可信,不堆排比,不用"随着…发展""总而言之"。',
    userPromptTemplate: '根据下面的青少年课程信息,写一份面向家长的招生文案,讲清适龄、课程收获、安全保障、师资与价格。只用已给信息,不夸大效果。\n\n---\n{{input}}\n---',
    temperature: 0.5
  }),
  base({
    id: 'analysis.clb-risk-review',
    label: '风险告知核查',
    shortLabel: '风险核查',
    icon: '🔍',
    tags: ['风险', '告知', '核查'],
    allowedActions: ['comment', 'link-comment', 'copy'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '核查攀岩风险告知书,指出缺漏与表述不清之处。',
    systemPrompt: '你是一位攀岩馆风控与合规专员,审查风险告知书文本。要求:逐条检查是否覆盖关键风险点(坠落、碰撞、装备失效、体能不适、年龄/健康限制、自愿参与、监护人签字等),指出缺漏、含糊或免责过度的表述,并引用原文逐字片段定位。只基于给定文本,不编造法规条款。仅辅助审查,不替代执业律师的法律意见,最终需专业法律审核。',
    userPromptTemplate: '审查下面的攀岩风险告知书,逐条列出问题,每条按如下格式:\n- 命中片段:`原文逐字片段`\n- 问题:缺漏/含糊/免责过度等\n- 建议:如何修改\n只基于给定文本,不编造法规。\n\n---\n{{input}}\n---',
    temperature: 0.3
  })
])

export function mergeClimbingIntoBuiltins(b = []) { const ids = new Set(b.map(x => x && x.id)); return [...b, ...CLIMBING_BUILTIN_ASSISTANTS.filter(x => x && !ids.has(x.id))] }

export default { CLIMBING_BUILTIN_ASSISTANTS }
