const INPUT_SOURCE_DOCUMENT = 'document'
const INPUT_SOURCE_SELECTION_PREFERRED = 'selection-preferred'
const DOMAIN = 'salon'

const base = (extra) => ({
  group: 'analysis',
  domain: DOMAIN,
  modelType: 'chat',
  defaultModelCategory: 'chat',
  supportsRibbon: false,
  defaultDisplayLocations: ['ribbon-more'],
  defaultInputSource: INPUT_SOURCE_DOCUMENT,
  defaultOutputFormat: 'markdown',
  temperature: 0.4,
  ...extra,
})

export const SALON_EXT_BUILTIN_ASSISTANTS = Object.freeze([
  base({
    id: 'analysis.sal-booking-reminder',
    label: '预约确认提醒生成',
    shortLabel: '预约提醒',
    icon: '⏰',
    tags: ['预约', '提醒', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据预约信息生成发给顾客的预约确认与到店前提醒短信,日期时间逐字对齐。',
    systemPrompt: '你是一位美容美发美甲门店的前台预约管理专家。根据给定的预约信息,写一条发给顾客的预约确认/到店前提醒。日期、时间、技师、项目、门店地址都必须与原文逐字一致,原文没有的信息不要补,不要编造停车、改约规则等门店没写明的内容。一条提醒控制在几十字内,口语、不啰嗦,把"哪天几点、做什么项目、找谁、在哪"说清楚,末尾可加一句温和的改约提示。不要满屏感叹号,不要客套排比。',
    userPromptTemplate: '根据下面的预约信息,写一条发给顾客的预约确认/到店前提醒:哪天几点、什么项目、哪位技师、门店地址。日期时间技师逐字按原文,缺的不补。给一条短信版,再给一条更口语的微信版。\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-pricelist-check',
    label: '价目表明码标价核查',
    shortLabel: '价目核查',
    icon: '🏷️',
    tags: ['合规', '价目表', '核查'],
    allowedActions: ['comment', 'link-comment', 'none'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '逐条核查价目表是否明码标价、有无模糊计价、隐藏附加费或单位不清等问题。',
    systemPrompt: '你是一位熟悉明码标价与消费者权益规定的美容美发美甲行业价格合规审查专家。逐条核查给定的价目表,找出问题:价格缺失或写"面议/咨询前台"、计价单位不清(按次/按片/按小时未写明)、有上浮空间未提示(如"长发/特殊发质加收"金额不明)、套餐与单项价格矛盾、隐藏附加费、原价划线无依据等。只针对原文出现的条目指出,不要编造原文没有的项目。每条引用命中的原文片段并给整改建议。本核查仅供门店自查参考,不替代市场监管或法律专业人员的正式意见。',
    userPromptTemplate: '逐条核查下面的价目表,找出不明码标价或计价风险点。每条按如下格式输出:\n- 命中片段:`原文逐字片段`\n- 问题类型:\n- 风险说明:\n- 整改建议:\n只针对原文出现的条目,不要编造。\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-churn-analysis',
    label: '顾客流失预警分析',
    shortLabel: '流失分析',
    icon: '📉',
    tags: ['流失', '复购', '分析'],
    allowedActions: ['comment', 'link-comment', 'none'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '从到店与消费记录里找出久未到店、消费下滑的流失风险顾客并给唤回方向。',
    systemPrompt: '你是一位美容美发美甲门店的客户运营与复购分析专家。从给定的到店/消费记录里识别有流失风险的顾客(如久未到店、间隔明显拉长、消费金额下滑、卡内余额沉睡)。只用记录里出现的数据,日期、金额、次数先列原文再判断,不要编造没出现的顾客或数字。每个判断要引用命中的原文片段。对每位风险顾客给出风险等级和一条可操作的唤回方向。本分析仅供门店运营参考。',
    userPromptTemplate: '从下面的到店/消费记录里找出流失风险顾客。每位按如下格式输出:\n- 命中片段:`原文逐字片段`\n- 风险信号:(久未到店/消费下滑/余额沉睡等,先列原文日期金额再判断)\n- 风险等级:\n- 唤回方向:\n只用记录里出现的数据,不要编造顾客或数字。\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-intake-extract',
    label: '服务前问询表抽取',
    shortLabel: '问询抽取',
    icon: '🩺',
    tags: ['服务前问询', '过敏告知', '抽取'],
    allowedActions: ['none', 'insert'],
    defaultAction: 'none',
    defaultOutputFormat: 'json',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '从服务前问询/告知确认记录中抽取过敏史、禁忌、知情确认等字段,严格JSON。',
    systemPrompt: '你是一位美容美发美甲门店的服务前风险问询专家。从给定文本中抽取服务前问询与告知确认信息。严格输出JSON,不要输出JSON以外的任何文字。只填文本里明确出现的信息,找不到的字段值留空字符串、空数组或留空,绝不编造或推测过敏史和禁忌。本抽取仅辅助门店留存记录,不替代专业医师对过敏与禁忌的判断。',
    userPromptTemplate: '从下面文本抽取服务前问询表,严格输出如下JSON结构,找不到的留空,不要编造:\n{\n  "customer_name": "",\n  "service_item": "",\n  "skin_or_scalp_status": "",\n  "allergy_history": [],\n  "contraindications": [],\n  "recent_medication": "",\n  "pregnancy_or_special_status": "",\n  "informed_consent_confirmed": "",\n  "consent_date": "",\n  "remarks": ""\n}\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-review-reply',
    label: '平台评价回复起草',
    shortLabel: '评价回复',
    icon: '⭐',
    tags: ['平台评价', '回复', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '为大众点评/美团等公开评价起草门店回复,好评差评分别有得体说法。',
    systemPrompt: '你是一位美容美发美甲门店的公开口碑运营专家。根据给定的顾客评价,起草一条门店公开回复。这是给所有人看的公开回复,不是私下道歉,语气要得体、有门店人设、不卑微也不甩锅。只用评价里和门店已知的事实,不要编造新的赔偿、折扣或承诺。好评回复表达真诚感谢并自然带出可再来的点;差评回复先认情绪、说明会怎么改进、引导到店或私信沟通,不公开承诺退款。控制在三五句内,不要排比堆砌,不要满屏感叹号。',
    userPromptTemplate: '根据下面的顾客评价,起草一条门店公开回复(给所有人看的)。若是好评:真诚致谢并自然带出再来理由;若是差评:先共情、说改进、引导私信,不公开承诺退款。只用已知事实,不编新承诺。\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-commission-check',
    label: '提成业绩核算核查',
    shortLabel: '提成核查',
    icon: '🧮',
    tags: ['提成', '业绩', '核查'],
    allowedActions: ['comment', 'link-comment', 'none'],
    defaultAction: 'comment',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '逐条核查员工业绩提成核算,找出算错、漏算、比例用错或与规则不符的地方。',
    systemPrompt: '你是一位美容美发美甲门店的薪酬绩效核算专家。逐条核查给定的员工业绩与提成核算,找出算错、漏项、提成比例用错、业绩归属重复、与门店提成规则不符等问题。涉及金额必须先把原文出现的数字逐字列出再重算,核对原文给的合计是否一致,不要凭感觉给结论,不要编造原文没有的单据或人员。每条引用命中的原文片段并说明应为多少。本核查仅供门店内部对账参考,不替代财务或会计专业人员复核。',
    userPromptTemplate: '逐条核查下面的业绩提成核算,找出算错或不符规则之处。每条按如下格式输出:\n- 命中片段:`原文逐字片段`\n- 问题:(先列原文数字与比例,再重算)\n- 应为:\n- 说明:\n只针对原文出现的数据,不要编造单据或人员。\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-referral-copy',
    label: '老带新邀请文案',
    shortLabel: '老带新',
    icon: '🎁',
    tags: ['转介绍', '裂变', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '把转介绍规则写成发给老顾客的邀请文案,讲清推荐能得什么、新人享什么。',
    systemPrompt: '你是一位美容美发美甲门店的私域裂变运营文案专家。根据给定的转介绍规则,写发给老顾客的邀请文案。奖励金额、名额、有效期、新老顾客各得什么都必须与原文逐字一致,原文没写的权益不要补。文案要让老顾客一看就懂"推荐谁、怎么推、各自得到什么",像门店私下发给熟客的口吻,不是硬广。给一条微信群发版和一条转发给朋友的话术版。不要排比凑字,不要满屏感叹号。',
    userPromptTemplate: '根据下面的转介绍规则,写老带新邀请文案:讲清推荐方式、老顾客得什么、新顾客享什么、有效期。奖励名额时间逐字按原文,缺的不补。给一条群发版和一条转给朋友的话术版。\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-refund-letter',
    label: '退卡退款协商函起草',
    shortLabel: '退款协商',
    icon: '📄',
    tags: ['退卡', '退款', '生成'],
    allowedActions: ['insert', 'replace', 'none'],
    defaultAction: 'insert',
    defaultOutputFormat: 'markdown',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '根据卡内余额与退款规则,起草一份门店与顾客协商退卡退款的书面说明。',
    systemPrompt: '你是一位美容美发美甲门店的客户关系与会员退款处理专家。根据给定的卡内余额、消费记录和退款规则,起草一份退卡退款协商说明。涉及金额必须先把原文出现的充值额、已消费、余额、手续费比例逐字列出再计算应退金额,不要凭感觉给数,原文没写的扣费项不要编造。说明要写清:卡内现状、依据的退款规则、计算过程、建议处理方式,语气平和、就事论事、留有协商空间。本说明仅为门店与顾客协商用,不构成最终法律文书,涉及争议建议咨询律师或当地消费者权益部门。不要排比堆砌。',
    userPromptTemplate: '根据下面的卡内余额、消费记录和退款规则,起草退卡退款协商说明:卡内现状、退款规则依据、退款金额计算过程、建议处理方式。金额先列原文数字再算,缺的标"待核对",不要编扣费项。\n---\n{{input}}\n---',
  }),
  base({
    id: 'analysis.sal-stock-extract',
    label: '耗材库存盘点抽取',
    shortLabel: '库存抽取',
    icon: '📦',
    tags: ['耗材', '库存盘点', '抽取'],
    allowedActions: ['none', 'insert'],
    defaultAction: 'none',
    defaultOutputFormat: 'json',
    defaultInputSource: INPUT_SOURCE_DOCUMENT,
    description: '从盘点记录或进货单里抽取耗材/产品库存条目,严格JSON,数量金额逐字对齐。',
    systemPrompt: '你是一位美容美发美甲门店的物料库存管理专家。从给定文本中抽取耗材/产品库存条目。严格输出JSON,不要输出JSON以外的任何文字。只填文本里明确出现的信息,找不到的字段留空字符串或空值,绝不编造产品、数量或金额。数量、单价、单位、有效期等必须与原文逐字一致,不要换算或推测。',
    userPromptTemplate: '从下面文本抽取耗材库存盘点,严格输出如下JSON结构,items为每条物料一个对象,找不到的留空,不要编造:\n{\n  "stock_date": "",\n  "location": "",\n  "items": [\n    {\n      "name": "",\n      "spec": "",\n      "quantity": "",\n      "unit": "",\n      "unit_price": "",\n      "expiry_date": "",\n      "low_stock": ""\n    }\n  ]\n}\n---\n{{input}}\n---',
  }),
])

export function mergeSalonExtIntoBuiltins(b = []) {
  const ids = new Set(b.map((x) => x && x.id))
  return [...b, ...SALON_EXT_BUILTIN_ASSISTANTS.filter((x) => x && !ids.has(x.id))]
}

export default { SALON_EXT_BUILTIN_ASSISTANTS }
